/**
 * Copyright (c) 2011, Regione Emilia-Romagna, Italy
 *  
 * Licensed under the EUPL, Version 1.1 or - as soon they
 * will be approved by the European Commission - subsequent
 * versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the
 * Licence.
 * 
 * For convenience a plain text copy of the English version
 * of the Licence can be found in the file LICENCE.txt in
 * the top-level directory of this software distribution.
 * 
 * You may obtain a copy of the Licence in any of 22 European
 * Languages at:
 * 
 * http://joinup.ec.europa.eu/software/page/eupl
 * 
 * Unless required by applicable law or agreed to in
 * writing, software distributed under the Licence is
 * distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied.
 * 
 * This product includes software developed by Yale University
 * 
 * See the Licence for the specific language governing
 * permissions and limitations under the Licence.
**/
/*

  Licenza:	    Licenza Progetto PEOPLE
  Fornitore:    CEFRIEL
  Autori:       M. Pianciamore, P. Selvini

  Questo codice sorgente � protetto dalla licenza valida nell'ambito del
  progetto PEOPLE. La propriet� intellettuale di questo codice � e rester�
  esclusiva di "CEFRIEL Societ� Consortile a Responsabilit� Limitata" con
  sede legale in via Renato Fucini 2, 20133 Milano (MI).

  Disclaimer:

  COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT
  WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT 
  LIMITATION, WARRANTIES THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE,
  FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS TO THE
  QUALITY AND PERFORMANCE OF THE COVERED CODE IS WITH YOU. SHOULD ANY COVERED
  CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT THE INITIAL DEVELOPER OR ANY
  OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY SERVICING, REPAIR OR
  CORRECTION.
    
*/
package it.idp.people.admin.sqlmap.sirac.accreditamenti;


public class Accreditamenti {
	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.codice_fiscale
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private String codiceFiscale;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.id_accreditamento
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private Integer idAccreditamento;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.id_comune
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private String idComune;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.id_qualifica
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private String idQualifica;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.codice_fiscale
     *
     * @return the value of accreditamenti.codice_fiscale
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.codice_fiscale
     *
     * @param codiceFiscale the value for accreditamenti.codice_fiscale
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setCodiceFiscale(String codiceFiscale) {
        this.codiceFiscale = codiceFiscale;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.id_accreditamento
     *
     * @return the value of accreditamenti.id_accreditamento
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public Integer getIdAccreditamento() {
        return idAccreditamento;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.id_accreditamento
     *
     * @param idAccreditamento the value for accreditamenti.id_accreditamento
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setIdAccreditamento(Integer idAccreditamento) {
        this.idAccreditamento = idAccreditamento;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.id_comune
     *
     * @return the value of accreditamenti.id_comune
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public String getIdComune() {
        return idComune;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.id_comune
     *
     * @param idComune the value for accreditamenti.id_comune
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setIdComune(String idComune) {
        this.idComune = idComune;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.id_qualifica
     *
     * @return the value of accreditamenti.id_qualifica
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public String getIdQualifica() {
        return idQualifica;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.id_qualifica
     *
     * @param idQualifica the value for accreditamenti.id_qualifica
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setIdQualifica(String idQualifica) {
        this.idQualifica = idQualifica;
    }
	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.domicilio_elettronico
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private String domicilioElettronico;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.codicefiscale_intermediario
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private String codicefiscaleIntermediario;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.partitaiva_intermediario
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private String partitaivaIntermediario;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.descrizione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private String descrizione;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.timestamp_certificazione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private String timestampCertificazione;    
    
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.sede_legale
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private String sedeLegale;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.denominazione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private String denominazione;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.attivo
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private Boolean attivo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.deleted
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private Boolean deleted;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.auto_certificazione_filename
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private String autoCertificazioneFilename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column accreditamenti.auto_certificazione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    private byte[] autoCertificazione;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.domicilio_elettronico
     *
     * @return the value of accreditamenti.domicilio_elettronico
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public String getDomicilioElettronico() {
        return domicilioElettronico;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.domicilio_elettronico
     *
     * @param domicilioElettronico the value for accreditamenti.domicilio_elettronico
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setDomicilioElettronico(String domicilioElettronico) {
        this.domicilioElettronico = domicilioElettronico;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.codicefiscale_intermediario
     *
     * @return the value of accreditamenti.codicefiscale_intermediario
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public String getCodicefiscaleIntermediario() {
        return codicefiscaleIntermediario;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.codicefiscale_intermediario
     *
     * @param codicefiscaleIntermediario the value for accreditamenti.codicefiscale_intermediario
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setCodicefiscaleIntermediario(String codicefiscaleIntermediario) {
        this.codicefiscaleIntermediario = codicefiscaleIntermediario;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.partitaiva_intermediario
     *
     * @return the value of accreditamenti.partitaiva_intermediario
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public String getPartitaivaIntermediario() {
        return partitaivaIntermediario;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.partitaiva_intermediario
     *
     * @param partitaivaIntermediario the value for accreditamenti.partitaiva_intermediario
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setPartitaivaIntermediario(String partitaivaIntermediario) {
        this.partitaivaIntermediario = partitaivaIntermediario;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.descrizione
     *
     * @return the value of accreditamenti.descrizione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.descrizione
     *
     * @param descrizione the value for accreditamenti.descrizione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.timestamp_certificazione
     *
     * @return the value of accreditamenti.timestamp_certificazione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public String getTimestampCertificazione() {
        return timestampCertificazione;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.timestamp_certificazione
     *
     * @param timestampCertificazione the value for accreditamenti.timestamp_certificazione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setTimestampCertificazione(String timestampCertificazione) {
        this.timestampCertificazione = timestampCertificazione;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.sede_legale
     *
     * @return the value of accreditamenti.sede_legale
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public String getSedeLegale() {
        return sedeLegale;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.sede_legale
     *
     * @param sedeLegale the value for accreditamenti.sede_legale
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setSedeLegale(String sedeLegale) {
        this.sedeLegale = sedeLegale;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.denominazione
     *
     * @return the value of accreditamenti.denominazione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public String getDenominazione() {
        return denominazione;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.denominazione
     *
     * @param denominazione the value for accreditamenti.denominazione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setDenominazione(String denominazione) {
        this.denominazione = denominazione;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.attivo
     *
     * @return the value of accreditamenti.attivo
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public Boolean getAttivo() {
    	return attivo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.attivo
     *
     * @param attivo the value for accreditamenti.attivo
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setAttivo(Boolean attivo) {
        this.attivo = attivo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.deleted
     *
     * @return the value of accreditamenti.deleted
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.deleted
     *
     * @param deleted the value for accreditamenti.deleted
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.auto_certificazione_filename
     *
     * @return the value of accreditamenti.auto_certificazione_filename
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public String getAutoCertificazioneFilename() {
        return autoCertificazioneFilename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.auto_certificazione_filename
     *
     * @param autoCertificazioneFilename the value for accreditamenti.auto_certificazione_filename
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setAutoCertificazioneFilename(String autoCertificazioneFilename) {
        this.autoCertificazioneFilename = autoCertificazioneFilename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column accreditamenti.auto_certificazione
     *
     * @return the value of accreditamenti.auto_certificazione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public byte[] getAutoCertificazione() {
        return autoCertificazione;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column accreditamenti.auto_certificazione
     *
     * @param autoCertificazione the value for accreditamenti.auto_certificazione
     *
     * @abatorgenerated Fri Jun 01 16:13:54 CEST 2007
     */
    public void setAutoCertificazione(byte[] autoCertificazione) {
        this.autoCertificazione = autoCertificazione;
    }

//	public String getDateCertificazione() 
//	{
//		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
//		Date date = null;
//		if(timestampCertificazione != null && !timestampCertificazione.equals(""))
//		{
//			date = new Date(Long.parseLong(timestampCertificazione));
//			dateCertificazione = dateFormat.format(date);			
//		}
//		else
//		{
//			dateCertificazione = "";
//		}
//		return dateCertificazione;
//	}

//	public void setDateCertificazione(String dateCertificazione) 
//	{
//		DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
//		try 
//		{
//			
//			timestampCertificazione = String.valueOf(dateFormat.parse(dateCertificazione).getTime());
//		} 
//		catch (ParseException e) 
//		{
//			timestampCertificazione = "";
//			e.printStackTrace();
//		}
//	}
}
