
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.wego.cross.avbari.linksmt.fascicolo;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-03-02T16:02:20.116+01:00
 * Generated source version: 2.3.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "FascicoloServerImplService",
                      portName = "FascicoloServerImplPort",
                      targetNamespace = "http://impl.server.ws.protocollo.linksmt.it/",
                      //PRODUZIONE
                      //wsdlLocation = "http://web99.linksmt.it/adoc/fascicolo?wsdl",
                      //LOCALE E TEST
                      //wsdlLocation = "fascicolo-wsdl/fascicolo.wsdl",
                      endpointInterface = "it.wego.cross.avbari.linksmt.fascicolo.FascicoloServer")
                      
public class FascicoloServerImpl implements FascicoloServer {

    private static final Logger LOG = LoggerFactory.getLogger(FascicoloServerImpl.class.getName());

    /* (non-Javadoc)
     * @see it.wego.cross.avbari.linksmt.fascicolo.FascicoloServer#fascicolaNuovoDocumento(it.wego.cross.avbari.linksmt.fascicolo.FascicolaNuovoDocumento.FascicolaNuovoDocumentoIN  fascicolaNuovoDocumentoIN )*
     */
    public it.wego.cross.avbari.linksmt.fascicolo.FascicolaNuovoDocumentoResponse.Return fascicolaNuovoDocumento(it.wego.cross.avbari.linksmt.fascicolo.FascicolaNuovoDocumento.FascicolaNuovoDocumentoIN fascicolaNuovoDocumentoIN) { 

        try {
            it.wego.cross.avbari.linksmt.fascicolo.FascicolaNuovoDocumentoResponse.Return _return = null;
            if( LOG.isInfoEnabled() )
            {
            	LOG.info("ESECUZIONE METODO [{}] DATI [{}] RISULTATO [{}]","fascicolaNuovoDocumento", fascicolaNuovoDocumentoIN, _return);
            }
            return _return;
        } catch (java.lang.Exception ex) {
        	if( LOG.isErrorEnabled() )
            {
            	LOG.error("ECCEZIONE ESECUZIONE METODO [{}] DATI [{}]","fascicolaNuovoDocumento", fascicolaNuovoDocumentoIN, ex);
            }
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.wego.cross.avbari.linksmt.fascicolo.FascicoloServer#creazioneFascicolo(it.wego.cross.avbari.linksmt.fascicolo.CreazioneFascicolo.NuovoFascicoloRequest  nuovoFascicoloRequest )*
     */
    public it.wego.cross.avbari.linksmt.fascicolo.CreazioneFascicoloResponse.Return creazioneFascicolo(it.wego.cross.avbari.linksmt.fascicolo.CreazioneFascicolo.NuovoFascicoloRequest nuovoFascicoloRequest) { 
        try {
            it.wego.cross.avbari.linksmt.fascicolo.CreazioneFascicoloResponse.Return _return = null;
            if( LOG.isInfoEnabled() )
            {
            	LOG.info("ESECUZIONE METODO [{}] DATI [{}] RISULTATO [{}]","creazioneFascicolo", nuovoFascicoloRequest, _return);
            }            
            return _return;
        } catch (java.lang.Exception ex) {
        	if( LOG.isErrorEnabled() )
            {
            	LOG.error("ECCEZIONE ESECUZIONE METODO [{}] DATI [{}]","creazioneFascicolo", nuovoFascicoloRequest, ex);
            }
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.wego.cross.avbari.linksmt.fascicolo.FascicoloServer#fascicolaDocProtocollato(it.wego.cross.avbari.linksmt.fascicolo.FascicolaDocProtocollato.FascicolaDocumentoRequest  fascicolaDocumentoRequest )*
     */
    public it.wego.cross.avbari.linksmt.fascicolo.FascicolaDocProtocollatoResponse.Return fascicolaDocProtocollato(it.wego.cross.avbari.linksmt.fascicolo.FascicolaDocProtocollato.FascicolaDocumentoRequest fascicolaDocumentoRequest) { 
        try {
            it.wego.cross.avbari.linksmt.fascicolo.FascicolaDocProtocollatoResponse.Return _return = null;
            if( LOG.isInfoEnabled() )
            {
            	LOG.info("ESECUZIONE METODO [{}] DATI [{}] RISULTATO [{}]","fascicolaDocProtocollato", fascicolaDocumentoRequest, _return);
            }             
            return _return;
        } catch (java.lang.Exception ex) {
        	if( LOG.isErrorEnabled() )
            {
            	LOG.error("ECCEZIONE ESECUZIONE METODO [{}] DATI [{}]","fascicolaDocProtocollato", fascicolaDocumentoRequest, ex);
            }
            throw new RuntimeException(ex);
        }
    }

}
