package it.wego.cross.avbari.linksmt.fascicolo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-03-02T16:02:20.136+01:00
 * Generated source version: 2.3.9
 * 
 */
@WebService(targetNamespace = "http://server.ws.protocollo.linksmt.it/", name = "FascicoloServer")
@XmlSeeAlso({ObjectFactory.class})
public interface FascicoloServer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fascicolaNuovoDocumento", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.fascicolo.FascicolaNuovoDocumento")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "fascicolaNuovoDocumentoResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.fascicolo.FascicolaNuovoDocumentoResponse")
    public it.wego.cross.avbari.linksmt.fascicolo.FascicolaNuovoDocumentoResponse.Return fascicolaNuovoDocumento(
        @WebParam(name = "fascicolaNuovoDocumentoIN", targetNamespace = "")
        it.wego.cross.avbari.linksmt.fascicolo.FascicolaNuovoDocumento.FascicolaNuovoDocumentoIN fascicolaNuovoDocumentoIN
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "creazioneFascicolo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.fascicolo.CreazioneFascicolo")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "creazioneFascicoloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.fascicolo.CreazioneFascicoloResponse")
    public it.wego.cross.avbari.linksmt.fascicolo.CreazioneFascicoloResponse.Return creazioneFascicolo(
        @WebParam(name = "nuovoFascicoloRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.fascicolo.CreazioneFascicolo.NuovoFascicoloRequest nuovoFascicoloRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fascicolaDocProtocollato", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.fascicolo.FascicolaDocProtocollato")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "fascicolaDocProtocollatoResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.fascicolo.FascicolaDocProtocollatoResponse")
    public it.wego.cross.avbari.linksmt.fascicolo.FascicolaDocProtocollatoResponse.Return fascicolaDocProtocollato(
        @WebParam(name = "fascicolaDocumentoRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.fascicolo.FascicolaDocProtocollato.FascicolaDocumentoRequest fascicolaDocumentoRequest
    );
}
