// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package it.wego.cross.client.stub.ricercaprotocollo;

public interface WSRicercaProtocollo extends java.rmi.Remote {
    public java.lang.String ricerca(java.lang.String codEnte, java.lang.String userid, java.lang.String password, java.lang.String indirizzoIP, java.lang.String xml, java.lang.String hash) throws 
         java.rmi.RemoteException;
}
