// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package it.wego.cross.client.stub.ricercaprotocollo;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class WSRicercaProtocollo_ricerca_ResponseStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private it.wego.cross.client.stub.ricercaprotocollo.WSRicercaProtocollo_ricerca_ResponseStruct _instance;
    private java.lang.String ricercaReturn;
    private static final int myRICERCARETURN_INDEX = 0;
    
    public WSRicercaProtocollo_ricerca_ResponseStruct_SOAPBuilder() {
    }
    
    public void setRicercaReturn(java.lang.String ricercaReturn) {
        this.ricercaReturn = ricercaReturn;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myRICERCARETURN_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myRICERCARETURN_INDEX:
                    _instance.setRicercaReturn((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (it.wego.cross.client.stub.ricercaprotocollo.WSRicercaProtocollo_ricerca_ResponseStruct)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
