// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package it.wego.cross.client.stub.ricercaprotocollo;


public class WSRicercaProtocollo_ricerca_RequestStruct {
    protected java.lang.String codEnte;
    protected java.lang.String userid;
    protected java.lang.String password;
    protected java.lang.String indirizzoIP;
    protected java.lang.String xml;
    protected java.lang.String hash;
    
    public WSRicercaProtocollo_ricerca_RequestStruct() {
    }
    
    public WSRicercaProtocollo_ricerca_RequestStruct(java.lang.String codEnte, java.lang.String userid, java.lang.String password, java.lang.String indirizzoIP, java.lang.String xml, java.lang.String hash) {
        this.codEnte = codEnte;
        this.userid = userid;
        this.password = password;
        this.indirizzoIP = indirizzoIP;
        this.xml = xml;
        this.hash = hash;
    }
    
    public java.lang.String getCodEnte() {
        return codEnte;
    }
    
    public void setCodEnte(java.lang.String codEnte) {
        this.codEnte = codEnte;
    }
    
    public java.lang.String getUserid() {
        return userid;
    }
    
    public void setUserid(java.lang.String userid) {
        this.userid = userid;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getIndirizzoIP() {
        return indirizzoIP;
    }
    
    public void setIndirizzoIP(java.lang.String indirizzoIP) {
        this.indirizzoIP = indirizzoIP;
    }
    
    public java.lang.String getXml() {
        return xml;
    }
    
    public void setXml(java.lang.String xml) {
        this.xml = xml;
    }
    
    public java.lang.String getHash() {
        return hash;
    }
    
    public void setHash(java.lang.String hash) {
        this.hash = hash;
    }
}
