// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package it.wego.cross.client.stub.ricercaprotocollo;


public class WSRicercaProtocollo_ricerca_ResponseStruct {
    protected java.lang.String ricercaReturn;
    
    public WSRicercaProtocollo_ricerca_ResponseStruct() {
    }
    
    public WSRicercaProtocollo_ricerca_ResponseStruct(java.lang.String ricercaReturn) {
        this.ricercaReturn = ricercaReturn;
    }
    
    public java.lang.String getRicercaReturn() {
        return ricercaReturn;
    }
    
    public void setRicercaReturn(java.lang.String ricercaReturn) {
        this.ricercaReturn = ricercaReturn;
    }
}
