// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package it.wego.cross.client.stub.ricercaprotocollo;

import javax.xml.rpc.*;

public interface WSRicercaProtocolloService extends javax.xml.rpc.Service {
    public it.wego.cross.client.stub.ricercaprotocollo.WSRicercaProtocollo getWSRicercaProtocollo(Integer timeout) throws ServiceException;
}
