//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 02:46:12 PM CEST 
//


package it.wego.cross.conferenzaservizi.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.wego.cross.conferenzaservizi.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.wego.cross.conferenzaservizi.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Seduta }
     * 
     */
    public Seduta createSeduta() {
        return new Seduta();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche }
     * 
     */
    public Seduta.Pratiche createSedutaPratiche() {
        return new Seduta.Pratiche();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica }
     * 
     */
    public Seduta.Pratiche.Pratica createSedutaPratichePratica() {
        return new Seduta.Pratiche.Pratica();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.ComponentiCommissione }
     * 
     */
    public Seduta.Pratiche.Pratica.ComponentiCommissione createSedutaPratichePraticaComponentiCommissione() {
        return new Seduta.Pratiche.Pratica.ComponentiCommissione();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.ComponentiCommissione.ComponenteCommissione }
     * 
     */
    public Seduta.Pratiche.Pratica.ComponentiCommissione.ComponenteCommissione createSedutaPratichePraticaComponentiCommissioneComponenteCommissione() {
        return new Seduta.Pratiche.Pratica.ComponentiCommissione.ComponenteCommissione();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Beneficiari }
     * 
     */
    public Seduta.Pratiche.Pratica.Beneficiari createSedutaPratichePraticaBeneficiari() {
        return new Seduta.Pratiche.Pratica.Beneficiari();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Richiedenti }
     * 
     */
    public Seduta.Pratiche.Pratica.Richiedenti createSedutaPratichePraticaRichiedenti() {
        return new Seduta.Pratiche.Pratica.Richiedenti();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Procedimento }
     * 
     */
    public Seduta.Pratiche.Pratica.Procedimento createSedutaPratichePraticaProcedimento() {
        return new Seduta.Pratiche.Pratica.Procedimento();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Procedimento.Endoprocedimenti }
     * 
     */
    public Seduta.Pratiche.Pratica.Procedimento.Endoprocedimenti createSedutaPratichePraticaProcedimentoEndoprocedimenti() {
        return new Seduta.Pratiche.Pratica.Procedimento.Endoprocedimenti();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Procedimento.Endoprocedimenti.Endoprocedimento }
     * 
     */
    public Seduta.Pratiche.Pratica.Procedimento.Endoprocedimenti.Endoprocedimento createSedutaPratichePraticaProcedimentoEndoprocedimentiEndoprocedimento() {
        return new Seduta.Pratiche.Pratica.Procedimento.Endoprocedimenti.Endoprocedimento();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Daticatastali }
     * 
     */
    public Seduta.Pratiche.Pratica.Daticatastali createSedutaPratichePraticaDaticatastali() {
        return new Seduta.Pratiche.Pratica.Daticatastali();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Daticatastali.Datocatastale }
     * 
     */
    public Seduta.Pratiche.Pratica.Daticatastali.Datocatastale createSedutaPratichePraticaDaticatastaliDatocatastale() {
        return new Seduta.Pratiche.Pratica.Daticatastali.Datocatastale();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Localizzazioni }
     * 
     */
    public Seduta.Pratiche.Pratica.Localizzazioni createSedutaPratichePraticaLocalizzazioni() {
        return new Seduta.Pratiche.Pratica.Localizzazioni();
    }

    /**
     * Create an instance of {@link Seduta.ComponentiCommissione }
     * 
     */
    public Seduta.ComponentiCommissione createSedutaComponentiCommissione() {
        return new Seduta.ComponentiCommissione();
    }

    /**
     * Create an instance of {@link Seduta.ComponentiCommissione.ComponenteCommissione }
     * 
     */
    public Seduta.ComponentiCommissione.ComponenteCommissione createSedutaComponentiCommissioneComponenteCommissione() {
        return new Seduta.ComponentiCommissione.ComponenteCommissione();
    }

    /**
     * Create an instance of {@link Seduta.DataConvocazione }
     * 
     */
    public Seduta.DataConvocazione createSedutaDataConvocazione() {
        return new Seduta.DataConvocazione();
    }

    /**
     * Create an instance of {@link Seduta.DataInizio }
     * 
     */
    public Seduta.DataInizio createSedutaDataInizio() {
        return new Seduta.DataInizio();
    }

    /**
     * Create an instance of {@link Seduta.DataConclusione }
     * 
     */
    public Seduta.DataConclusione createSedutaDataConclusione() {
        return new Seduta.DataConclusione();
    }

    /**
     * Create an instance of {@link Seduta.Ente }
     * 
     */
    public Seduta.Ente createSedutaEnte() {
        return new Seduta.Ente();
    }

    /**
     * Create an instance of {@link Seduta.Organo }
     * 
     */
    public Seduta.Organo createSedutaOrgano() {
        return new Seduta.Organo();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.ComponentiCommissione.ComponenteCommissione.Ruolo }
     * 
     */
    public Seduta.Pratiche.Pratica.ComponentiCommissione.ComponenteCommissione.Ruolo createSedutaPratichePraticaComponentiCommissioneComponenteCommissioneRuolo() {
        return new Seduta.Pratiche.Pratica.ComponentiCommissione.ComponenteCommissione.Ruolo();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Beneficiari.Beneficiario }
     * 
     */
    public Seduta.Pratiche.Pratica.Beneficiari.Beneficiario createSedutaPratichePraticaBeneficiariBeneficiario() {
        return new Seduta.Pratiche.Pratica.Beneficiari.Beneficiario();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Richiedenti.Richiedente }
     * 
     */
    public Seduta.Pratiche.Pratica.Richiedenti.Richiedente createSedutaPratichePraticaRichiedentiRichiedente() {
        return new Seduta.Pratiche.Pratica.Richiedenti.Richiedente();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Procedimento.Endoprocedimenti.Endoprocedimento.Ente }
     * 
     */
    public Seduta.Pratiche.Pratica.Procedimento.Endoprocedimenti.Endoprocedimento.Ente createSedutaPratichePraticaProcedimentoEndoprocedimentiEndoprocedimentoEnte() {
        return new Seduta.Pratiche.Pratica.Procedimento.Endoprocedimenti.Endoprocedimento.Ente();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Daticatastali.Datocatastale.Tipocatasto }
     * 
     */
    public Seduta.Pratiche.Pratica.Daticatastali.Datocatastale.Tipocatasto createSedutaPratichePraticaDaticatastaliDatocatastaleTipocatasto() {
        return new Seduta.Pratiche.Pratica.Daticatastali.Datocatastale.Tipocatasto();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Daticatastali.Datocatastale.Tipounita }
     * 
     */
    public Seduta.Pratiche.Pratica.Daticatastali.Datocatastale.Tipounita createSedutaPratichePraticaDaticatastaliDatocatastaleTipounita() {
        return new Seduta.Pratiche.Pratica.Daticatastali.Datocatastale.Tipounita();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Daticatastali.Datocatastale.Tipoparticella }
     * 
     */
    public Seduta.Pratiche.Pratica.Daticatastali.Datocatastale.Tipoparticella createSedutaPratichePraticaDaticatastaliDatocatastaleTipoparticella() {
        return new Seduta.Pratiche.Pratica.Daticatastali.Datocatastale.Tipoparticella();
    }

    /**
     * Create an instance of {@link Seduta.Pratiche.Pratica.Localizzazioni.Localizzazione }
     * 
     */
    public Seduta.Pratiche.Pratica.Localizzazioni.Localizzazione createSedutaPratichePraticaLocalizzazioniLocalizzazione() {
        return new Seduta.Pratiche.Pratica.Localizzazioni.Localizzazione();
    }

    /**
     * Create an instance of {@link Seduta.ComponentiCommissione.ComponenteCommissione.Ruolo }
     * 
     */
    public Seduta.ComponentiCommissione.ComponenteCommissione.Ruolo createSedutaComponentiCommissioneComponenteCommissioneRuolo() {
        return new Seduta.ComponentiCommissione.ComponenteCommissione.Ruolo();
    }

}
