//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 09:11:56 AM CET 
//


package it.wego.cross.avbari.catasto.client.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.wego.cross.avbari.catasto.client.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CodEnte_QNAME = new QName("", "CodEnte");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.wego.cross.avbari.catasto.client.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link PrecompilazioneBean }
     * 
     */
    public PrecompilazioneBean createPrecompilazioneBean() {
        return new PrecompilazioneBean();
    }

    /**
     * Create an instance of {@link Input.CampoPrecompilazioneBean }
     * 
     */
    public Input.CampoPrecompilazioneBean createInputCampoPrecompilazioneBean() {
        return new Input.CampoPrecompilazioneBean();
    }

    /**
     * Create an instance of {@link Output.CampoPrecompilazioneBean }
     * 
     */
    public Output.CampoPrecompilazioneBean createOutputCampoPrecompilazioneBean() {
        return new Output.CampoPrecompilazioneBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodEnte")
    public JAXBElement<String> createCodEnte(String value) {
        return new JAXBElement<String>(_CodEnte_QNAME, String.class, null, value);
    }

}
