// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetStrade_ResponseStruct {

    protected java.lang.String wsGetStradeReturn;

    public Toponomastica_wsGetStrade_ResponseStruct() {
    }

    public Toponomastica_wsGetStrade_ResponseStruct(java.lang.String wsGetStradeReturn) {
        this.wsGetStradeReturn = wsGetStradeReturn;
    }

    public java.lang.String getWsGetStradeReturn() {
        return wsGetStradeReturn;
    }

    public void setWsGetStradeReturn(java.lang.String wsGetStradeReturn) {
        this.wsGetStradeReturn = wsGetStradeReturn;
    }
}
