// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.streaming.*;
import javax.xml.namespace.QName;

public class Toponomastica_main_ResponseStruct_SOAPSerializer extends ObjectSerializerBase implements Initializable {

    public Toponomastica_main_ResponseStruct_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }

    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
    }

    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
            SOAPDeserializationContext context) throws java.lang.Exception {
        Toponomastica_main_ResponseStruct instance = new Toponomastica_main_ResponseStruct();
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;

        reader.nextElementContent();
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object) instance : (java.lang.Object) state);
    }

    @Override
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        Toponomastica_main_ResponseStruct instance = (Toponomastica_main_ResponseStruct) obj;

    }

    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        Toponomastica_main_ResponseStruct instance = (Toponomastica_main_ResponseStruct) obj;

    }

    @Override
    protected void verifyName(XMLReader reader, javax.xml.namespace.QName expectedName) throws java.lang.Exception {
    }
}
