// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetEsistenzaCivico_ResponseStruct {

    protected java.lang.String wsGetEsistenzaCivicoReturn;

    public Toponomastica_wsGetEsistenzaCivico_ResponseStruct() {
    }

    public Toponomastica_wsGetEsistenzaCivico_ResponseStruct(java.lang.String wsGetEsistenzaCivicoReturn) {
        this.wsGetEsistenzaCivicoReturn = wsGetEsistenzaCivicoReturn;
    }

    public java.lang.String getWsGetEsistenzaCivicoReturn() {
        return wsGetEsistenzaCivicoReturn;
    }

    public void setWsGetEsistenzaCivicoReturn(java.lang.String wsGetEsistenzaCivicoReturn) {
        this.wsGetEsistenzaCivicoReturn = wsGetEsistenzaCivicoReturn;
    }
}
