// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetStrada_ResponseStruct {

    protected java.lang.String wsGetStradaReturn;

    public Toponomastica_wsGetStrada_ResponseStruct() {
    }

    public Toponomastica_wsGetStrada_ResponseStruct(java.lang.String wsGetStradaReturn) {
        this.wsGetStradaReturn = wsGetStradaReturn;
    }

    public java.lang.String getWsGetStradaReturn() {
        return wsGetStradaReturn;
    }

    public void setWsGetStradaReturn(java.lang.String wsGetStradaReturn) {
        this.wsGetStradaReturn = wsGetStradaReturn;
    }
}
