// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetCivici_ResponseStruct {

    protected java.lang.String wsGetCiviciReturn;

    public Toponomastica_wsGetCivici_ResponseStruct() {
    }

    public Toponomastica_wsGetCivici_ResponseStruct(java.lang.String wsGetCiviciReturn) {
        this.wsGetCiviciReturn = wsGetCiviciReturn;
    }

    public java.lang.String getWsGetCiviciReturn() {
        return wsGetCiviciReturn;
    }

    public void setWsGetCiviciReturn(java.lang.String wsGetCiviciReturn) {
        this.wsGetCiviciReturn = wsGetCiviciReturn;
    }
}
