// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetExecUpdate_ResponseStruct {

    protected java.lang.String wsGetExecUpdateReturn;

    public Toponomastica_wsGetExecUpdate_ResponseStruct() {
    }

    public Toponomastica_wsGetExecUpdate_ResponseStruct(java.lang.String wsGetExecUpdateReturn) {
        this.wsGetExecUpdateReturn = wsGetExecUpdateReturn;
    }

    public java.lang.String getWsGetExecUpdateReturn() {
        return wsGetExecUpdateReturn;
    }

    public void setWsGetExecUpdateReturn(java.lang.String wsGetExecUpdateReturn) {
        this.wsGetExecUpdateReturn = wsGetExecUpdateReturn;
    }
}
