// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetCivico_ResponseStruct {

    protected java.lang.String wsGetCivicoReturn;

    public Toponomastica_wsGetCivico_ResponseStruct() {
    }

    public Toponomastica_wsGetCivico_ResponseStruct(java.lang.String wsGetCivicoReturn) {
        this.wsGetCivicoReturn = wsGetCivicoReturn;
    }

    public java.lang.String getWsGetCivicoReturn() {
        return wsGetCivicoReturn;
    }

    public void setWsGetCivicoReturn(java.lang.String wsGetCivicoReturn) {
        this.wsGetCivicoReturn = wsGetCivicoReturn;
    }
}
