// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetDatiCatastaliDaToponomastici_ResponseStruct {

    protected java.lang.String wsGetDatiCatastaliDaToponomasticiReturn;

    public Toponomastica_wsGetDatiCatastaliDaToponomastici_ResponseStruct() {
    }

    public Toponomastica_wsGetDatiCatastaliDaToponomastici_ResponseStruct(java.lang.String wsGetDatiCatastaliDaToponomasticiReturn) {
        this.wsGetDatiCatastaliDaToponomasticiReturn = wsGetDatiCatastaliDaToponomasticiReturn;
    }

    public java.lang.String getWsGetDatiCatastaliDaToponomasticiReturn() {
        return wsGetDatiCatastaliDaToponomasticiReturn;
    }

    public void setWsGetDatiCatastaliDaToponomasticiReturn(java.lang.String wsGetDatiCatastaliDaToponomasticiReturn) {
        this.wsGetDatiCatastaliDaToponomasticiReturn = wsGetDatiCatastaliDaToponomasticiReturn;
    }
}
