// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetInterno_ResponseStruct {

    protected java.lang.String wsGetInternoReturn;

    public Toponomastica_wsGetInterno_ResponseStruct() {
    }

    public Toponomastica_wsGetInterno_ResponseStruct(java.lang.String wsGetInternoReturn) {
        this.wsGetInternoReturn = wsGetInternoReturn;
    }

    public java.lang.String getWsGetInternoReturn() {
        return wsGetInternoReturn;
    }

    public void setWsGetInternoReturn(java.lang.String wsGetInternoReturn) {
        this.wsGetInternoReturn = wsGetInternoReturn;
    }
}
