// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsProtocolloDestinatariInterniDirezioni_RequestStruct {

    protected java.lang.String sXmlFile;

    public Toponomastica_wsProtocolloDestinatariInterniDirezioni_RequestStruct() {
    }

    public Toponomastica_wsProtocolloDestinatariInterniDirezioni_RequestStruct(java.lang.String sXmlFile) {
        this.sXmlFile = sXmlFile;
    }

    public java.lang.String getSXmlFile() {
        return sXmlFile;
    }

    public void setSXmlFile(java.lang.String sXmlFile) {
        this.sXmlFile = sXmlFile;
    }
}
