// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetEsistenzaInterno_ResponseStruct {

    protected java.lang.String wsGetEsistenzaInternoReturn;

    public Toponomastica_wsGetEsistenzaInterno_ResponseStruct() {
    }

    public Toponomastica_wsGetEsistenzaInterno_ResponseStruct(java.lang.String wsGetEsistenzaInternoReturn) {
        this.wsGetEsistenzaInternoReturn = wsGetEsistenzaInternoReturn;
    }

    public java.lang.String getWsGetEsistenzaInternoReturn() {
        return wsGetEsistenzaInternoReturn;
    }

    public void setWsGetEsistenzaInternoReturn(java.lang.String wsGetEsistenzaInternoReturn) {
        this.wsGetEsistenzaInternoReturn = wsGetEsistenzaInternoReturn;
    }
}
