// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class ToponomasticaService_SerializerRegistry implements SerializerConstants {

    public ToponomasticaService_SerializerRegistry() {
    }

    public TypeMappingRegistry getRegistry() {

        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
        TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
        TypeMapping mapping2 = registry.getTypeMapping("");
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetEsistenzaCivicoResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetEsistenzaCivico_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetEsistenzaCivico_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetEsistenzaInternoResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetEsistenzaInterno_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetEsistenzaInterno_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetResidentiDaCodiceFiscaleResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetResidentiDaCodiceFiscale_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetResidentiDaCodiceFiscale_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetStradaResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetStrada_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetStrada_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsProtocolloDestinatariInterniDirezioniResponse");
            CombinedSerializer serializer = new Toponomastica_wsProtocolloDestinatariInterniDirezioni_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsProtocolloDestinatariInterniDirezioni_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetInterni");
            CombinedSerializer serializer = new Toponomastica_wsGetInterni_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetInterni_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetCivico");
            CombinedSerializer serializer = new Toponomastica_wsGetCivico_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetCivico_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetSezioneFoglioMappaleDaToponomastici");
            CombinedSerializer serializer = new Toponomastica_wsGetSezioneFoglioMappaleDaToponomastici_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetSezioneFoglioMappaleDaToponomastici_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetCiviciConZonaCensuaria");
            CombinedSerializer serializer = new Toponomastica_wsGetCiviciConZonaCensuaria_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetCiviciConZonaCensuaria_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetEsistenzaInterno");
            CombinedSerializer serializer = new Toponomastica_wsGetEsistenzaInterno_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetEsistenzaInterno_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetResidentiDaToponomastica");
            CombinedSerializer serializer = new Toponomastica_wsGetResidentiDaToponomastica_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetResidentiDaToponomastica_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "processResponse");
            CombinedSerializer serializer = new Toponomastica_process_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_process_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetDatiToponomasticiDaCatastali");
            CombinedSerializer serializer = new Toponomastica_wsGetDatiToponomasticiDaCatastali_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetDatiToponomasticiDaCatastali_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetCivici");
            CombinedSerializer serializer = new Toponomastica_wsGetCivici_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetCivici_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetInterno");
            CombinedSerializer serializer = new Toponomastica_wsGetInterno_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetInterno_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "ArrayOf_xsd_string");
            QName elemName = new QName("", "item");
            CombinedSerializer serializer = new ObjectArraySerializer(type,
                    ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING,
                    elemName, SchemaConstants.QNAME_TYPE_STRING, java.lang.String.class, 1, null, SOAPVersion.SOAP_11);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, java.lang.String[].class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetCivicoResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetCivico_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetCivico_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetEsistenzaCivico");
            CombinedSerializer serializer = new Toponomastica_wsGetEsistenzaCivico_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetEsistenzaCivico_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "process");
            CombinedSerializer serializer = new Toponomastica_process_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_process_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetLocationPathUpdateResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetLocationPathUpdate_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetLocationPathUpdate_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetDatiToponomasticiDaCatastaliResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetDatiToponomasticiDaCatastali_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetDatiToponomasticiDaCatastali_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetCiviciResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetCivici_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetCivici_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetExecUpdate");
            CombinedSerializer serializer = new Toponomastica_wsGetExecUpdate_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetExecUpdate_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetDatiCatastaliDaToponomastici");
            CombinedSerializer serializer = new Toponomastica_wsGetDatiCatastaliDaToponomastici_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetDatiCatastaliDaToponomastici_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetSezioneFoglioMappaleDaToponomasticiResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetSezioneFoglioMappaleDaToponomastici_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetSezioneFoglioMappaleDaToponomastici_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetStradaCategorieCosap");
            CombinedSerializer serializer = new Toponomastica_wsGetStradaCategorieCosap_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetStradaCategorieCosap_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetInternoResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetInterno_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetInterno_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetInterniResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetInterni_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetInterni_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetReleaseEdiliziaOnLineResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetReleaseEdiliziaOnLine_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetReleaseEdiliziaOnLine_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetResidentiDaToponomasticaResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetResidentiDaToponomastica_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetResidentiDaToponomastica_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsProtocolloDestinatariInterniDirezioni");
            CombinedSerializer serializer = new Toponomastica_wsProtocolloDestinatariInterniDirezioni_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsProtocolloDestinatariInterniDirezioni_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetDatiCatastaliDaToponomasticiResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetDatiCatastaliDaToponomastici_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetDatiCatastaliDaToponomastici_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetStradeResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetStrade_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetStrade_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsProtocolloDestinatariInterniResponse");
            CombinedSerializer serializer = new Toponomastica_wsProtocolloDestinatariInterni_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsProtocolloDestinatariInterni_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetStrada");
            CombinedSerializer serializer = new Toponomastica_wsGetStrada_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetStrada_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetReleaseEdiliziaOnLine");
            CombinedSerializer serializer = new Toponomastica_wsGetReleaseEdiliziaOnLine_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetReleaseEdiliziaOnLine_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetRangeCivici");
            CombinedSerializer serializer = new Toponomastica_wsGetRangeCivici_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetRangeCivici_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetExecUpdateResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetExecUpdate_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetExecUpdate_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetStradaCategorieCosapResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetStradaCategorieCosap_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetStradaCategorieCosap_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetResidentiDaCodiceFiscale");
            CombinedSerializer serializer = new Toponomastica_wsGetResidentiDaCodiceFiscale_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetResidentiDaCodiceFiscale_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "main");
            CombinedSerializer serializer = new Toponomastica_main_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_main_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "mainResponse");
            CombinedSerializer serializer = new Toponomastica_main_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_main_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "testHTTP");
            CombinedSerializer serializer = new Toponomastica_testHTTP_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_testHTTP_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetLocationPathUpdate");
            CombinedSerializer serializer = new Toponomastica_wsGetLocationPathUpdate_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetLocationPathUpdate_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetRangeCiviciResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetRangeCivici_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetRangeCivici_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetStrade");
            CombinedSerializer serializer = new Toponomastica_wsGetStrade_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetStrade_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsGetCiviciConZonaCensuariaResponse");
            CombinedSerializer serializer = new Toponomastica_wsGetCiviciConZonaCensuaria_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsGetCiviciConZonaCensuaria_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "testHTTPResponse");
            CombinedSerializer serializer = new Toponomastica_testHTTP_ResponseStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_testHTTP_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://wstoponomastica.comune.genova.it:8080/toponomastica/Toponomastica.jws", "wsProtocolloDestinatariInterni");
            CombinedSerializer serializer = new Toponomastica_wsProtocolloDestinatariInterni_RequestStruct_SOAPSerializer(type,
                    DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping, Toponomastica_wsProtocolloDestinatariInterni_RequestStruct.class, type, serializer);
        }
        return registry;
    }

    private static void registerSerializer(TypeMapping mapping, java.lang.Class javaType, javax.xml.namespace.QName xmlType,
            Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
                new SingletonDeserializerFactory((Deserializer) ser));
    }
}
