// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsProtocolloDestinatariInterni_ResponseStruct {

    protected java.lang.String wsProtocolloDestinatariInterniReturn;

    public Toponomastica_wsProtocolloDestinatariInterni_ResponseStruct() {
    }

    public Toponomastica_wsProtocolloDestinatariInterni_ResponseStruct(java.lang.String wsProtocolloDestinatariInterniReturn) {
        this.wsProtocolloDestinatariInterniReturn = wsProtocolloDestinatariInterniReturn;
    }

    public java.lang.String getWsProtocolloDestinatariInterniReturn() {
        return wsProtocolloDestinatariInterniReturn;
    }

    public void setWsProtocolloDestinatariInterniReturn(java.lang.String wsProtocolloDestinatariInterniReturn) {
        this.wsProtocolloDestinatariInterniReturn = wsProtocolloDestinatariInterniReturn;
    }
}
