// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetResidentiDaCodiceFiscale_ResponseStruct {

    protected java.lang.String wsGetResidentiDaCodiceFiscaleReturn;

    public Toponomastica_wsGetResidentiDaCodiceFiscale_ResponseStruct() {
    }

    public Toponomastica_wsGetResidentiDaCodiceFiscale_ResponseStruct(java.lang.String wsGetResidentiDaCodiceFiscaleReturn) {
        this.wsGetResidentiDaCodiceFiscaleReturn = wsGetResidentiDaCodiceFiscaleReturn;
    }

    public java.lang.String getWsGetResidentiDaCodiceFiscaleReturn() {
        return wsGetResidentiDaCodiceFiscaleReturn;
    }

    public void setWsGetResidentiDaCodiceFiscaleReturn(java.lang.String wsGetResidentiDaCodiceFiscaleReturn) {
        this.wsGetResidentiDaCodiceFiscaleReturn = wsGetResidentiDaCodiceFiscaleReturn;
    }
}
