// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_main_RequestStruct {

    protected java.lang.String[] args;

    public Toponomastica_main_RequestStruct() {
    }

    public Toponomastica_main_RequestStruct(java.lang.String[] args) {
        this.args = args;
    }

    public java.lang.String[] getArgs() {
        return args;
    }

    public void setArgs(java.lang.String[] args) {
        this.args = args;
    }
}
