// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetReleaseEdiliziaOnLine_ResponseStruct {

    protected java.lang.String wsGetReleaseEdiliziaOnLineReturn;

    public Toponomastica_wsGetReleaseEdiliziaOnLine_ResponseStruct() {
    }

    public Toponomastica_wsGetReleaseEdiliziaOnLine_ResponseStruct(java.lang.String wsGetReleaseEdiliziaOnLineReturn) {
        this.wsGetReleaseEdiliziaOnLineReturn = wsGetReleaseEdiliziaOnLineReturn;
    }

    public java.lang.String getWsGetReleaseEdiliziaOnLineReturn() {
        return wsGetReleaseEdiliziaOnLineReturn;
    }

    public void setWsGetReleaseEdiliziaOnLineReturn(java.lang.String wsGetReleaseEdiliziaOnLineReturn) {
        this.wsGetReleaseEdiliziaOnLineReturn = wsGetReleaseEdiliziaOnLineReturn;
    }
}
