// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_wsGetResidentiDaToponomastica_ResponseStruct {

    protected java.lang.String wsGetResidentiDaToponomasticaReturn;

    public Toponomastica_wsGetResidentiDaToponomastica_ResponseStruct() {
    }

    public Toponomastica_wsGetResidentiDaToponomastica_ResponseStruct(java.lang.String wsGetResidentiDaToponomasticaReturn) {
        this.wsGetResidentiDaToponomasticaReturn = wsGetResidentiDaToponomasticaReturn;
    }

    public java.lang.String getWsGetResidentiDaToponomasticaReturn() {
        return wsGetResidentiDaToponomasticaReturn;
    }

    public void setWsGetResidentiDaToponomasticaReturn(java.lang.String wsGetResidentiDaToponomasticaReturn) {
        this.wsGetResidentiDaToponomasticaReturn = wsGetResidentiDaToponomasticaReturn;
    }
}
