// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3
package it.wego.cross.genova.anagrafe.client.stub;

public class Toponomastica_testHTTP_RequestStruct {

    protected java.lang.String test;

    public Toponomastica_testHTTP_RequestStruct() {
    }

    public Toponomastica_testHTTP_RequestStruct(java.lang.String test) {
        this.test = test;
    }

    public java.lang.String getTest() {
        return test;
    }

    public void setTest(java.lang.String test) {
        this.test = test;
    }
}
