INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.user','user', 'Username per l\'autenticazione sul protocollo');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.password','password', 'Password per l\'autenticazione sul protocollo');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.codice.ente','', 'Codice ente');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.timeout','10000', 'Timeout chiamata al protocollo');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.endpoint.ricercaanagrafica','', 'Endpoint del servizio di ricerca anagrafica');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.endpoint.inseriscifascicolo','', 'Endpoint del servizio di inserimento del fascicolo');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.endpoint.ricercaprotocollo','', 'Endpoint del servizio di ricerca del protocollo');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.endpoint','', 'Endpoint del servizio di protocollo');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.id.uo.in','', 'ID UO IN');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.id.uo.prov','', 'ID UO PROV - Struttura di provenienza');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.id.ute.in','', 'ID UTE IN');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.numero.fascicolo','', 'Numero di fascicolo');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.subject','', 'Oggetto');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.id.titolazione','', 'ID della titolazione');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.id.indice.copie','', 'ID indice delle copie');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.copy.ouc.in','', 'COPY OUC IN');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.copy.ous.in','', 'COPY OUS IN');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.copy.post.in','', 'COPY POST IN');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.copy.serv.in','', 'COPY SERV IN');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.copy.sett.in','', 'COPY SETT IN');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.destinatario.ind.telem.tipo','', 'Tipologia di indirizzo telematico del destinatario');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.id.fascicolo','', 'ID Fascicolo');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.id.indice','', 'ID Indice');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.id.postazione','', 'ID Postazione Lavoro');
INSERT INTO configuration (NAME, VALUE, note) VALUES ('protocollo.egrammata.anno.fascicolo','', 'Anno fascicolo');