/**
 * Copyright (c) 2011, Regione Emilia-Romagna, Italy
 *  
 * Licensed under the EUPL, Version 1.1 or - as soon they
 * will be approved by the European Commission - subsequent
 * versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the
 * Licence.
 * 
 * For convenience a plain text copy of the English version
 * of the Licence can be found in the file LICENCE.txt in
 * the top-level directory of this software distribution.
 * 
 * You may obtain a copy of the Licence in any of 22 European
 * Languages at:
 * 
 * http://joinup.ec.europa.eu/software/page/eupl
 * 
 * Unless required by applicable law or agreed to in
 * writing, software distributed under the Licence is
 * distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied.
 * 
 * This product includes software developed by Yale University
 * 
 * See the Licence for the specific language governing
 * permissions and limitations under the Licence.
**/
/*

  Licenza:	    Licenza Progetto PEOPLE
  Fornitore:    CEFRIEL
  Autori:       M. Pianciamore, P. Selvini

  Questo codice sorgente � protetto dalla licenza valida nell'ambito del
  progetto PEOPLE. La propriet� intellettuale di questo codice � e rester�
  esclusiva di "CEFRIEL Societ� Consortile a Responsabilit� Limitata" con
  sede legale in via Renato Fucini 2, 20133 Milano (MI).

  Disclaimer:

  COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT
  WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT 
  LIMITATION, WARRANTIES THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE,
  FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS TO THE
  QUALITY AND PERFORMANCE OF THE COVERED CODE IS WITH YOU. SHOULD ANY COVERED
  CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT THE INITIAL DEVELOPER OR ANY
  OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY SERVICING, REPAIR OR
  CORRECTION.
    
*/
package it.idp.people.admin.sqlmap.sirac.qualifiche;

public class Qualifiche {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qualifiche.id_qualifica
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    private String idQualifica;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qualifiche.descrizione
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    private String descrizione;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qualifiche.tipo_qualifica
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    private String tipoQualifica;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qualifiche.auto_certificabile
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    private Boolean autoCertificabile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column qualifiche.has_rappresentante_legale
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    private Boolean hasRappresentanteLegale;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qualifiche.id_qualifica
     *
     * @return the value of qualifiche.id_qualifica
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    public String getIdQualifica() {
        return idQualifica;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qualifiche.id_qualifica
     *
     * @param idQualifica the value for qualifiche.id_qualifica
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    public void setIdQualifica(String idQualifica) {
        this.idQualifica = idQualifica;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qualifiche.descrizione
     *
     * @return the value of qualifiche.descrizione
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qualifiche.descrizione
     *
     * @param descrizione the value for qualifiche.descrizione
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qualifiche.tipo_qualifica
     *
     * @return the value of qualifiche.tipo_qualifica
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    public String getTipoQualifica() {
        return tipoQualifica;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qualifiche.tipo_qualifica
     *
     * @param tipoQualifica the value for qualifiche.tipo_qualifica
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    public void setTipoQualifica(String tipoQualifica) {
        this.tipoQualifica = tipoQualifica;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qualifiche.auto_certificabile
     *
     * @return the value of qualifiche.auto_certificabile
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    public Boolean getAutoCertificabile() {
        return autoCertificabile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qualifiche.auto_certificabile
     *
     * @param autoCertificabile the value for qualifiche.auto_certificabile
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    public void setAutoCertificabile(Boolean autoCertificabile) {
        this.autoCertificabile = autoCertificabile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column qualifiche.has_rappresentante_legale
     *
     * @return the value of qualifiche.has_rappresentante_legale
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    public Boolean getHasRappresentanteLegale() {
        return hasRappresentanteLegale;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column qualifiche.has_rappresentante_legale
     *
     * @param hasRappresentanteLegale the value for qualifiche.has_rappresentante_legale
     *
     * @abatorgenerated Fri May 25 16:40:01 CEST 2007
     */
    public void setHasRappresentanteLegale(Boolean hasRappresentanteLegale) {
        this.hasRappresentanteLegale = hasRappresentanteLegale;
    }
}
