cd AllegatiService/
mvn tomcat7:redeploy
cd ../DynamicOdtServiceWego/
mvn tomcat7:redeploy
cd ../FEService
mvn tomcat7:redeploy
cd ../firmasemplice
mvn tomcat7:redeploy
cd ../people
mvn tomcat7:redeploy
cd ../PeopleService
mvn tomcat7:redeploy
cd ../SimpleDesk
mvn tomcat7:redeploy
