[#ftl]
	
[#function getValue data field type="" emptypattern=""]
    [#assign completefieldname="data."+field]
    [#assign datafield=completefieldname?eval]
    [#if type=="date"]
        [#return  datafield?string("dd/MM/yyyy")]
    [/#if]
    [#if type=="text" || type=="string" || type==""]
        [#if emptypattern==datafield?string]
            [#return  ""]
        [/#if]
        [#return  datafield]
    [/#if]
[/#function]