<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is JAX-WS RI 2.2-hudson-740-. --><wsdl:definitions xmlns:axis2="http://people.dbm.it" xmlns:xyz="http://people.dbm.it" xmlns:ns1="http://org.apache.axis2/xsd" xmlns:urn="http://people.dbm.it/xsd" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:fi="http://java.sun.com/xml/ns/wsit/2006/09/policy/fastinfoset/service" xmlns:tcp="http://java.sun.com/xml/ns/wsit/2006/09/policy/soaptcp/service" targetNamespace="http://people.dbm.it">
    <wsdl:documentation>
    	    Dynamic Odt generation from Odt template to several outputs
    </wsdl:documentation>
    <wsdl:types>
        <xs:schema xmlns:axis2="http://people.dbm.it" xmlns:ns="http://people.dbm.it/xsd" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://people.dbm.it/xsd">
		<xs:import schemaLocation="http://localhost:8080/TCR/Pubblicazione?xsd=1" namespace="http://people.dbm.it" />
            
            <xs:element name="generateDocumentResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="return" nillable="true" type="xs:base64Binary" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="generateDocumentRequest">
        <wsdl:part name="part1" element="xyz:documentRoot" />
    </wsdl:message>
    <wsdl:message name="generateDocumentResponse">
        <wsdl:part name="part1" element="urn:generateDocumentResponse" />
    </wsdl:message>
    <wsdl:portType name="PubblicazionePortType">
        <wsdl:operation name="generateDocument">
            <wsdl:input message="axis2:generateDocumentRequest" wsaw:Action="xyz:documentRoot" />
            <wsdl:output message="axis2:generateDocumentResponse" wsaw:Action="generateDocumentResponse" />
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="PubblicazioneSOAP11Binding" type="axis2:PubblicazionePortType">
        <wsp:PolicyReference URI="#PubblicazioneSOAP11BindingPolicy" />
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="generateDocument">
            <soap:operation soapAction="urn:generateDocument" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="PubblicazioneSOAP12Binding" type="axis2:PubblicazionePortType">
        <wsp:PolicyReference URI="#PubblicazioneSOAP12BindingPolicy" />
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="generateDocument">
            <soap12:operation soapAction="urn:generateDocument" style="document" />
            <wsdl:input>
                <soap12:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="PubblicazioneHttpBinding" type="axis2:PubblicazionePortType">
        <wsp:PolicyReference URI="#PubblicazioneHttpBindingPolicy" />
        <http:binding verb="POST" />
        <wsdl:operation name="generateDocument">
            <http:operation location="generateDocument" />
            <wsdl:input>
                <mime:content type="text/xml" />
            </wsdl:input>
            <wsdl:output>
                <mime:content type="text/xml" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="Pubblicazione">
        <wsdl:port name="PubblicazioneSOAP11port_http" binding="axis2:PubblicazioneSOAP11Binding">
            <soap:address location="http://localhost:8080/TCR/Pubblicazione" />
        </wsdl:port>
        <wsdl:port name="PubblicazioneSOAP12port_http" binding="axis2:PubblicazioneSOAP12Binding">
            <soap12:address location="http://demo.reporter.it:8000/Pubblicazione/services/Pubblicazione" />
        </wsdl:port>
        <wsdl:port name="PubblicazioneHttpport1" binding="axis2:PubblicazioneHttpBinding">
            <http:address location="http://demo.reporter.it:8000/Pubblicazione/rest/Pubblicazione" />
        </wsdl:port>
    </wsdl:service>
    <wsp:Policy wsu:Id="PubblicazioneSOAP11BindingPolicy">
        <wsp:ExactlyOne>
            <wsp:All />
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="PubblicazioneHttpBindingPolicy">
        <wsp:ExactlyOne>
            <wsp:All />
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="PubblicazioneSOAP12BindingPolicy">
        <wsp:ExactlyOne>
            <wsp:All />
        </wsp:ExactlyOne>
    </wsp:Policy>
</wsdl:definitions>