
package it.wego.cross.avbari.sit.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IntegrazioneSueSuap", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://web02test.hsh.it/wsIntegrazioneSueSuap/IntegrazioneSueSuap.svc?wsdl")
public class IntegrazioneSueSuap  extends Service
{

    private final static URL INTEGRAZIONESUESUAP_WSDL_LOCATION;
    private final static WebServiceException INTEGRAZIONESUESUAP_EXCEPTION;
    private final static QName INTEGRAZIONESUESUAP_QNAME = new QName("http://tempuri.org/", "IntegrazioneSueSuap");
    private static final Logger logger = LoggerFactory.getLogger(IntegrazioneSueSuap.class.getName());
    static {
        URL url = null;
        WebServiceException e = null;
        String wsdlClasspathUrl = "it/wego/cross/avbari/linksmt/wsdl_produzione/02_05_2018/sitIntegrazioneSuapSue/wsdl_integrazione_suap_sue.wsdl";
        try {
        	Resource res = new ClassPathResource(wsdlClasspathUrl);
            url = res.getURL();
        } catch (Exception ex) {
        	logger.warn("Impossibile inizializzare l'URL del WS per le determine accedendo al file del classpath {} ", wsdlClasspathUrl, e);
        	e = new WebServiceException(ex);
        }
        INTEGRAZIONESUESUAP_WSDL_LOCATION = url;
        INTEGRAZIONESUESUAP_EXCEPTION = e;
    }

    public IntegrazioneSueSuap() {
        super(__getWsdlLocation(), INTEGRAZIONESUESUAP_QNAME);
    }

    public IntegrazioneSueSuap(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTEGRAZIONESUESUAP_QNAME, features);
    }

    public IntegrazioneSueSuap(URL wsdlLocation) {
        super(wsdlLocation, INTEGRAZIONESUESUAP_QNAME);
    }

    public IntegrazioneSueSuap(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTEGRAZIONESUESUAP_QNAME, features);
    }

    public IntegrazioneSueSuap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegrazioneSueSuap(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IIntegrazioneSueSuap
     */
    @WebEndpoint(name = "BasicHttpBinding_IIntegrazioneSueSuap")
    public IIntegrazioneSueSuap getBasicHttpBindingIIntegrazioneSueSuap() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IIntegrazioneSueSuap"), IIntegrazioneSueSuap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IIntegrazioneSueSuap
     */
    @WebEndpoint(name = "BasicHttpBinding_IIntegrazioneSueSuap")
    public IIntegrazioneSueSuap getBasicHttpBindingIIntegrazioneSueSuap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IIntegrazioneSueSuap"), IIntegrazioneSueSuap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEGRAZIONESUESUAP_EXCEPTION!= null) {
            throw INTEGRAZIONESUESUAP_EXCEPTION;
        }
        return INTEGRAZIONESUESUAP_WSDL_LOCATION;
    }

}
