/**
 * Copyright (c) 2011, Regione Emilia-Romagna, Italy
 *  
 * Licensed under the EUPL, Version 1.1 or - as soon they
 * will be approved by the European Commission - subsequent
 * versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the
 * Licence.
 * 
 * For convenience a plain text copy of the English version
 * of the Licence can be found in the file LICENCE.txt in
 * the top-level directory of this software distribution.
 * 
 * You may obtain a copy of the Licence in any of 22 European
 * Languages at:
 * 
 * http://joinup.ec.europa.eu/software/page/eupl
 * 
 * Unless required by applicable law or agreed to in
 * writing, software distributed under the Licence is
 * distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied.
 * 
 * This product includes software developed by Yale University
 * 
 * See the Licence for the specific language governing
 * permissions and limitations under the Licence.
**/
/*

  Licenza:	    Licenza Progetto PEOPLE
  Fornitore:    CEFRIEL
  Autori:       M. Pianciamore, P. Selvini

  Questo codice sorgente � protetto dalla licenza valida nell'ambito del
  progetto PEOPLE. La propriet� intellettuale di questo codice � e rester�
  esclusiva di "CEFRIEL Societ� Consortile a Responsabilit� Limitata" con
  sede legale in via Renato Fucini 2, 20133 Milano (MI).

  Disclaimer:

  COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT
  WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT 
  LIMITATION, WARRANTIES THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE,
  FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS TO THE
  QUALITY AND PERFORMANCE OF THE COVERED CODE IS WITH YOU. SHOULD ANY COVERED
  CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT THE INITIAL DEVELOPER OR ANY
  OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY SERVICING, REPAIR OR
  CORRECTION.
    
*/
package it.idp.people.admin.sqlmap.capeople.userdata;

import java.sql.Timestamp;

public class Userdata {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.CODICE_FISCALE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String codiceFiscale;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.CARTA_IDENTITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String cartaIdentita;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.NOME
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String nome;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.COGNOME
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String cognome;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.DATA_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String dataNascita;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.CAP_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String capDomicilio;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.CAP_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String capResidenza;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.CITTA_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String cittaDomicilio;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.CITTA_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String cittaResidenza;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.INDIRIZZO_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String indirizzoDomicilio;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.INDIRIZZO_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String indirizzoResidenza;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.LAVORO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String lavoro;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.LUOGO_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String luogoNascita;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.PROVINCIA_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String provinciaDomicilio;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.PROVINCIA_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String provinciaNascita;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.PROVINCIA_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String provinciaResidenza;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.SESSO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String sesso = "M";

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.STATO_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String statoDomicilio;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.STATO_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String statoResidenza;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.STATO_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String statoNascita;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.TELEFONO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String telefono;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.CELLULARE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String cellulare;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.TITOLO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String titolo;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.E_MAIL
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String email;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.DOMICILIO_ELETTRONICO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String domicilioElettronico;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.ID_COMUNE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String idComune;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.PASSWORD
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String password;

	private boolean passwordChanged = false;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.PIN
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String pin;
	
	private boolean pinChanged = false;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.DATA_REGISTRAZIONE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private Timestamp dataRegistrazione;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.DATA_ATTIVAZIONE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private Timestamp dataAttivazione;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column userdata.STATUS
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	private String status;
	
	private String ruolo;
	
	private String territorio;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.CODICE_FISCALE
	 * 
	 * @return the value of userdata.CODICE_FISCALE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getCodiceFiscale() {
		return codiceFiscale;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.CODICE_FISCALE
	 * 
	 * @param codiceFiscale
	 *            the value for userdata.CODICE_FISCALE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.CARTA_IDENTITA
	 * 
	 * @return the value of userdata.CARTA_IDENTITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getCartaIdentita() {
		return cartaIdentita;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.CARTA_IDENTITA
	 * 
	 * @param cartaIdentita
	 *            the value for userdata.CARTA_IDENTITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setCartaIdentita(String cartaIdentita) {
		this.cartaIdentita = cartaIdentita;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.NOME
	 * 
	 * @return the value of userdata.NOME
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.NOME
	 * 
	 * @param nome
	 *            the value for userdata.NOME
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.COGNOME
	 * 
	 * @return the value of userdata.COGNOME
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getCognome() {
		return cognome;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.COGNOME
	 * 
	 * @param cognome
	 *            the value for userdata.COGNOME
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.DATA_NASCITA
	 * 
	 * @return the value of userdata.DATA_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getDataNascita() {
		return dataNascita;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.DATA_NASCITA
	 * 
	 * @param dataNascita
	 *            the value for userdata.DATA_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setDataNascita(String dataNascita) {
		this.dataNascita = dataNascita;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.CAP_DOMICILIO
	 * 
	 * @return the value of userdata.CAP_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getCapDomicilio() {
		return capDomicilio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.CAP_DOMICILIO
	 * 
	 * @param capDomicilio
	 *            the value for userdata.CAP_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setCapDomicilio(String capDomicilio) {
		this.capDomicilio = capDomicilio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.CAP_RESIDENZA
	 * 
	 * @return the value of userdata.CAP_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getCapResidenza() {
		return capResidenza;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.CAP_RESIDENZA
	 * 
	 * @param capResidenza
	 *            the value for userdata.CAP_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setCapResidenza(String capResidenza) {
		this.capResidenza = capResidenza;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.CITTA_DOMICILIO
	 * 
	 * @return the value of userdata.CITTA_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getCittaDomicilio() {
		return cittaDomicilio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.CITTA_DOMICILIO
	 * 
	 * @param cittaDomicilio
	 *            the value for userdata.CITTA_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setCittaDomicilio(String cittaDomicilio) {
		this.cittaDomicilio = cittaDomicilio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.CITTA_RESIDENZA
	 * 
	 * @return the value of userdata.CITTA_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getCittaResidenza() {
		return cittaResidenza;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.CITTA_RESIDENZA
	 * 
	 * @param cittaResidenza
	 *            the value for userdata.CITTA_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setCittaResidenza(String cittaResidenza) {
		this.cittaResidenza = cittaResidenza;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.INDIRIZZO_DOMICILIO
	 * 
	 * @return the value of userdata.INDIRIZZO_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getIndirizzoDomicilio() {
		return indirizzoDomicilio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.INDIRIZZO_DOMICILIO
	 * 
	 * @param indirizzoDomicilio
	 *            the value for userdata.INDIRIZZO_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setIndirizzoDomicilio(String indirizzoDomicilio) {
		this.indirizzoDomicilio = indirizzoDomicilio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.INDIRIZZO_RESIDENZA
	 * 
	 * @return the value of userdata.INDIRIZZO_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getIndirizzoResidenza() {
		return indirizzoResidenza;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.INDIRIZZO_RESIDENZA
	 * 
	 * @param indirizzoResidenza
	 *            the value for userdata.INDIRIZZO_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setIndirizzoResidenza(String indirizzoResidenza) {
		this.indirizzoResidenza = indirizzoResidenza;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.LAVORO
	 * 
	 * @return the value of userdata.LAVORO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getLavoro() {
		return lavoro;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.LAVORO
	 * 
	 * @param lavoro
	 *            the value for userdata.LAVORO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setLavoro(String lavoro) {
		this.lavoro = lavoro;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.LUOGO_NASCITA
	 * 
	 * @return the value of userdata.LUOGO_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getLuogoNascita() {
		return luogoNascita;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.LUOGO_NASCITA
	 * 
	 * @param luogoNascita
	 *            the value for userdata.LUOGO_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setLuogoNascita(String luogoNascita) {
		this.luogoNascita = luogoNascita;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.PROVINCIA_DOMICILIO
	 * 
	 * @return the value of userdata.PROVINCIA_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getProvinciaDomicilio() {
		return provinciaDomicilio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.PROVINCIA_DOMICILIO
	 * 
	 * @param provinciaDomicilio
	 *            the value for userdata.PROVINCIA_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setProvinciaDomicilio(String provinciaDomicilio) {
		this.provinciaDomicilio = provinciaDomicilio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.PROVINCIA_NASCITA
	 * 
	 * @return the value of userdata.PROVINCIA_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getProvinciaNascita() {
		return provinciaNascita;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.PROVINCIA_NASCITA
	 * 
	 * @param provinciaNascita
	 *            the value for userdata.PROVINCIA_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setProvinciaNascita(String provinciaNascita) {
		this.provinciaNascita = provinciaNascita;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.PROVINCIA_RESIDENZA
	 * 
	 * @return the value of userdata.PROVINCIA_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getProvinciaResidenza() {
		return provinciaResidenza;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.PROVINCIA_RESIDENZA
	 * 
	 * @param provinciaResidenza
	 *            the value for userdata.PROVINCIA_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setProvinciaResidenza(String provinciaResidenza) {
		this.provinciaResidenza = provinciaResidenza;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.SESSO
	 * 
	 * @return the value of userdata.SESSO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getSesso() {
		return sesso;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.SESSO
	 * 
	 * @param sesso
	 *            the value for userdata.SESSO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setSesso(String sesso) {
		this.sesso = sesso;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.STATO_DOMICILIO
	 * 
	 * @return the value of userdata.STATO_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getStatoDomicilio() {
		return statoDomicilio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.STATO_DOMICILIO
	 * 
	 * @param statoDomicilio
	 *            the value for userdata.STATO_DOMICILIO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setStatoDomicilio(String statoDomicilio) {
		this.statoDomicilio = statoDomicilio;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.STATO_RESIDENZA
	 * 
	 * @return the value of userdata.STATO_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getStatoResidenza() {
		return statoResidenza;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.STATO_RESIDENZA
	 * 
	 * @param statoResidenza
	 *            the value for userdata.STATO_RESIDENZA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setStatoResidenza(String statoResidenza) {
		this.statoResidenza = statoResidenza;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.STATO_NASCITA
	 * 
	 * @return the value of userdata.STATO_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getStatoNascita() {
		return statoNascita;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.STATO_NASCITA
	 * 
	 * @param statoNascita
	 *            the value for userdata.STATO_NASCITA
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setStatoNascita(String statoNascita) {
		this.statoNascita = statoNascita;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.TELEFONO
	 * 
	 * @return the value of userdata.TELEFONO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.TELEFONO
	 * 
	 * @param telefono
	 *            the value for userdata.TELEFONO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.CELLULARE
	 * 
	 * @return the value of userdata.CELLULARE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getCellulare() {
		return cellulare;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.CELLULARE
	 * 
	 * @param cellulare
	 *            the value for userdata.CELLULARE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setCellulare(String cellulare) {
		this.cellulare = cellulare;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.TITOLO
	 * 
	 * @return the value of userdata.TITOLO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getTitolo() {
		return titolo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.TITOLO
	 * 
	 * @param titolo
	 *            the value for userdata.TITOLO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setTitolo(String titolo) {
		this.titolo = titolo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.E_MAIL
	 * 
	 * @return the value of userdata.E_MAIL
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.E_MAIL
	 * 
	 * @param eMail
	 *            the value for userdata.E_MAIL
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setEmail(String eMail) {
		this.email = eMail;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.DOMICILIO_ELETTRONICO
	 * 
	 * @return the value of userdata.DOMICILIO_ELETTRONICO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getDomicilioElettronico() {
		return domicilioElettronico;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.DOMICILIO_ELETTRONICO
	 * 
	 * @param domicilioElettronico
	 *            the value for userdata.DOMICILIO_ELETTRONICO
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setDomicilioElettronico(String domicilioElettronico) {
		this.domicilioElettronico = domicilioElettronico;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.ID_COMUNE
	 * 
	 * @return the value of userdata.ID_COMUNE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getIdComune() {
		return idComune;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.ID_COMUNE
	 * 
	 * @param idComune
	 *            the value for userdata.ID_COMUNE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setIdComune(String idComune) {
		this.idComune = idComune;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.PASSWORD
	 * 
	 * @return the value of userdata.PASSWORD
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.PASSWORD
	 * 
	 * @param password
	 *            the value for userdata.PASSWORD
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setPassword(String password) {
		if (this.password != null && !this.password.equals(password)) {
			passwordChanged = true;
		} else {
			passwordChanged = false;
		}
		this.password = password;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.PIN
	 * 
	 * @return the value of userdata.PIN
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getPin() {
		return pin;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.PIN
	 * 
	 * @param pin
	 *            the value for userdata.PIN
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setPin(String pin) {
		if (this.pin != null && !this.pin.equals(pin)) {
			pinChanged = true;
		} else {
			pinChanged = false;
		}
		this.pin = pin;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.DATA_REGISTRAZIONE
	 * 
	 * @return the value of userdata.DATA_REGISTRAZIONE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public Timestamp getDataRegistrazione() {
		return dataRegistrazione;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.DATA_REGISTRAZIONE
	 * 
	 * @param dataRegistrazione
	 *            the value for userdata.DATA_REGISTRAZIONE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setDataRegistrazione(Timestamp dataRegistrazione) {
		this.dataRegistrazione = dataRegistrazione;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.DATA_ATTIVAZIONE
	 * 
	 * @return the value of userdata.DATA_ATTIVAZIONE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public Timestamp getDataAttivazione() {
		return dataAttivazione;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.DATA_ATTIVAZIONE
	 * 
	 * @param dataAttivazione
	 *            the value for userdata.DATA_ATTIVAZIONE
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setDataAttivazione(Timestamp dataAttivazione) {
		this.dataAttivazione = dataAttivazione;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column userdata.STATUS
	 * 
	 * @return the value of userdata.STATUS
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column userdata.STATUS
	 * 
	 * @param status
	 *            the value for userdata.STATUS
	 * 
	 * @abatorgenerated Mon Apr 23 12:46:34 CEST 2007
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	public boolean isPasswordChanged() {
		return passwordChanged;
	}
	
	public boolean isPinChanged() {
		return pinChanged;
	}

	/**
	 * @return the ruolo
	 */
	public String getRuolo() {
		return this.ruolo;
	}

	/**
	 * @param ruolo the ruolo to set
	 */
	public void setRuolo(String ruolo) {
		this.ruolo = ruolo;
	}

	/**
	 * @return the territorio
	 */
	public String getTerritorio() {
		return this.territorio;
	}

	/**
	 * @param territorio the territorio to set
	 */
	public void setTerritorio(String territorio) {
		this.territorio = territorio;
	}
	
}
