
package it.eng.tz.avtmb.wsdl.stampsign;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2020-11-10T16:12:25.593+01:00
 * Generated source version: 2.3.9
 * 
 */
public final class DocumentStampSignPt_DocumentStampSignBinding_Client {

    private static final QName SERVICE_NAME = new QName("http://stampsign.wsdl.avtmb.tz.eng.it", "stampsign");

    private DocumentStampSignPt_DocumentStampSignBinding_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Stampsign.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Stampsign ss = new Stampsign(wsdlURL, SERVICE_NAME);
        DocumentStampSignPt port = ss.getDocumentStampSignBinding();  
        
        {
        System.out.println("Invoking documentStampSign...");
        it.eng.tz.avtmb.xsd.stampsign.StampSignRequest _documentStampSign_documentStampSignInPart = null;
        it.eng.tz.avtmb.xsd.stampsign.StampSignResponse _documentStampSign__return = port.documentStampSign(_documentStampSign_documentStampSignInPart);
        System.out.println("documentStampSign.result=" + _documentStampSign__return);


        }

        System.exit(0);
    }

}
