//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 02:24:43 PM CEST 
//


package it.wego.cross.plugins.genova.commercio.xml.ermes.richiesta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codicelegacy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codicedomanda" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statodomanda" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="motivazione" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codicelegacy",
    "codicedomanda",
    "statodomanda",
    "motivazione"
})
@XmlRootElement(name = "DatiAggiornamentoDomanda")
public class DatiAggiornamentoDomanda {

    @XmlElement(required = true)
    protected String codicelegacy;
    @XmlElement(required = true)
    protected String codicedomanda;
    @XmlElement(required = true)
    protected String statodomanda;
    @XmlElement(required = true)
    protected String motivazione;

    /**
     * Gets the value of the codicelegacy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodicelegacy() {
        return codicelegacy;
    }

    /**
     * Sets the value of the codicelegacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodicelegacy(String value) {
        this.codicelegacy = value;
    }

    /**
     * Gets the value of the codicedomanda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodicedomanda() {
        return codicedomanda;
    }

    /**
     * Sets the value of the codicedomanda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodicedomanda(String value) {
        this.codicedomanda = value;
    }

    /**
     * Gets the value of the statodomanda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatodomanda() {
        return statodomanda;
    }

    /**
     * Sets the value of the statodomanda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatodomanda(String value) {
        this.statodomanda = value;
    }

    /**
     * Gets the value of the motivazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotivazione() {
        return motivazione;
    }

    /**
     * Sets the value of the motivazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotivazione(String value) {
        this.motivazione = value;
    }

}
