//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.08 at 11:11:55 AM CET 
//


package it.people.xsd.visura;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AltriSoggettiType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AltriSoggettiType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoRapporto" type="{http://myPage.init.it/VisuraTypes}RuoloType"/>
 *         &lt;element name="soggetto" type="{http://myPage.init.it/VisuraTypes}AnagrafeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AltriSoggettiType", propOrder = {
    "tipoRapporto",
    "soggetto"
})
public class AltriSoggettiType {

    @XmlElement(required = true)
    protected RuoloType tipoRapporto;
    @XmlElement(required = true)
    protected AnagrafeType soggetto;

    /**
     * Gets the value of the tipoRapporto property.
     * 
     * @return
     *     possible object is
     *     {@link RuoloType }
     *     
     */
    public RuoloType getTipoRapporto() {
        return tipoRapporto;
    }

    /**
     * Sets the value of the tipoRapporto property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuoloType }
     *     
     */
    public void setTipoRapporto(RuoloType value) {
        this.tipoRapporto = value;
    }

    /**
     * Gets the value of the soggetto property.
     * 
     * @return
     *     possible object is
     *     {@link AnagrafeType }
     *     
     */
    public AnagrafeType getSoggetto() {
        return soggetto;
    }

    /**
     * Sets the value of the soggetto property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagrafeType }
     *     
     */
    public void setSoggetto(AnagrafeType value) {
        this.soggetto = value;
    }

}
