//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.08 at 11:11:55 AM CET 
//


package it.people.xsd.visura;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DettaglioPraticaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DettaglioPraticaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idPratica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idProcedimento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroPratica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataPratica" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="numeroProtocolloGenerale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataProtocolloGenerale" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="richiedente" type="{http://myPage.init.it/VisuraTypes}AnagrafeType"/>
 *         &lt;element name="intermediario" type="{http://myPage.init.it/VisuraTypes}AnagrafeType" minOccurs="0"/>
 *         &lt;element name="altriSoggetti" type="{http://myPage.init.it/VisuraTypes}AltriSoggettiType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="oggetto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="intervento" type="{http://myPage.init.it/VisuraTypes}InterventoType" minOccurs="0"/>
 *         &lt;element name="localizzazione" type="{http://myPage.init.it/VisuraTypes}LocalizzazioneNelComuneType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="documenti" type="{http://myPage.init.it/VisuraTypes}DocumentiType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="altriDati" type="{http://myPage.init.it/VisuraTypes}ParametroType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="procedimenti" type="{http://myPage.init.it/VisuraTypes}ProcedimentoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="schede" type="{http://myPage.init.it/VisuraTypes}SchedaType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DettaglioPraticaType", propOrder = {
    "idPratica",
    "idProcedimento",
    "numeroPratica",
    "dataPratica",
    "numeroProtocolloGenerale",
    "dataProtocolloGenerale",
    "richiedente",
    "intermediario",
    "altriSoggetti",
    "oggetto",
    "intervento",
    "localizzazione",
    "documenti",
    "altriDati",
    "procedimenti",
    "schede"
})
public class DettaglioPraticaType {

    @XmlElement(required = true)
    protected String idPratica;
    protected String idProcedimento;
    @XmlElement(required = true)
    protected String numeroPratica;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataPratica;
    protected String numeroProtocolloGenerale;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataProtocolloGenerale;
    @XmlElement(required = true)
    protected AnagrafeType richiedente;
    protected AnagrafeType intermediario;
    protected List<AltriSoggettiType> altriSoggetti;
    @XmlElement(required = true)
    protected String oggetto;
    protected InterventoType intervento;
    protected List<LocalizzazioneNelComuneType> localizzazione;
    protected List<DocumentiType> documenti;
    protected List<ParametroType> altriDati;
    protected List<ProcedimentoType> procedimenti;
    protected List<SchedaType> schede;

    /**
     * Gets the value of the idPratica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdPratica() {
        return idPratica;
    }

    /**
     * Sets the value of the idPratica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdPratica(String value) {
        this.idPratica = value;
    }

    /**
     * Gets the value of the idProcedimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdProcedimento() {
        return idProcedimento;
    }

    /**
     * Sets the value of the idProcedimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdProcedimento(String value) {
        this.idProcedimento = value;
    }

    /**
     * Gets the value of the numeroPratica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroPratica() {
        return numeroPratica;
    }

    /**
     * Sets the value of the numeroPratica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroPratica(String value) {
        this.numeroPratica = value;
    }

    /**
     * Gets the value of the dataPratica property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataPratica() {
        return dataPratica;
    }

    /**
     * Sets the value of the dataPratica property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataPratica(XMLGregorianCalendar value) {
        this.dataPratica = value;
    }

    /**
     * Gets the value of the numeroProtocolloGenerale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroProtocolloGenerale() {
        return numeroProtocolloGenerale;
    }

    /**
     * Sets the value of the numeroProtocolloGenerale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroProtocolloGenerale(String value) {
        this.numeroProtocolloGenerale = value;
    }

    /**
     * Gets the value of the dataProtocolloGenerale property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataProtocolloGenerale() {
        return dataProtocolloGenerale;
    }

    /**
     * Sets the value of the dataProtocolloGenerale property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataProtocolloGenerale(XMLGregorianCalendar value) {
        this.dataProtocolloGenerale = value;
    }

    /**
     * Gets the value of the richiedente property.
     * 
     * @return
     *     possible object is
     *     {@link AnagrafeType }
     *     
     */
    public AnagrafeType getRichiedente() {
        return richiedente;
    }

    /**
     * Sets the value of the richiedente property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagrafeType }
     *     
     */
    public void setRichiedente(AnagrafeType value) {
        this.richiedente = value;
    }

    /**
     * Gets the value of the intermediario property.
     * 
     * @return
     *     possible object is
     *     {@link AnagrafeType }
     *     
     */
    public AnagrafeType getIntermediario() {
        return intermediario;
    }

    /**
     * Sets the value of the intermediario property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagrafeType }
     *     
     */
    public void setIntermediario(AnagrafeType value) {
        this.intermediario = value;
    }

    /**
     * Gets the value of the altriSoggetti property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altriSoggetti property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltriSoggetti().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AltriSoggettiType }
     * 
     * 
     */
    public List<AltriSoggettiType> getAltriSoggetti() {
        if (altriSoggetti == null) {
            altriSoggetti = new ArrayList<AltriSoggettiType>();
        }
        return this.altriSoggetti;
    }

    /**
     * Gets the value of the oggetto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOggetto() {
        return oggetto;
    }

    /**
     * Sets the value of the oggetto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOggetto(String value) {
        this.oggetto = value;
    }

    /**
     * Gets the value of the intervento property.
     * 
     * @return
     *     possible object is
     *     {@link InterventoType }
     *     
     */
    public InterventoType getIntervento() {
        return intervento;
    }

    /**
     * Sets the value of the intervento property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterventoType }
     *     
     */
    public void setIntervento(InterventoType value) {
        this.intervento = value;
    }

    /**
     * Gets the value of the localizzazione property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localizzazione property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalizzazione().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocalizzazioneNelComuneType }
     * 
     * 
     */
    public List<LocalizzazioneNelComuneType> getLocalizzazione() {
        if (localizzazione == null) {
            localizzazione = new ArrayList<LocalizzazioneNelComuneType>();
        }
        return this.localizzazione;
    }

    /**
     * Gets the value of the documenti property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documenti property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumenti().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentiType }
     * 
     * 
     */
    public List<DocumentiType> getDocumenti() {
        if (documenti == null) {
            documenti = new ArrayList<DocumentiType>();
        }
        return this.documenti;
    }

    /**
     * Gets the value of the altriDati property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altriDati property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltriDati().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParametroType }
     * 
     * 
     */
    public List<ParametroType> getAltriDati() {
        if (altriDati == null) {
            altriDati = new ArrayList<ParametroType>();
        }
        return this.altriDati;
    }

    /**
     * Gets the value of the procedimenti property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the procedimenti property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcedimenti().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcedimentoType }
     * 
     * 
     */
    public List<ProcedimentoType> getProcedimenti() {
        if (procedimenti == null) {
            procedimenti = new ArrayList<ProcedimentoType>();
        }
        return this.procedimenti;
    }

    /**
     * Gets the value of the schede property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schede property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchede().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchedaType }
     * 
     * 
     */
    public List<SchedaType> getSchede() {
        if (schede == null) {
            schede = new ArrayList<SchedaType>();
        }
        return this.schede;
    }

}
