//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.08 at 11:11:55 AM CET 
//


package it.people.xsd.visura;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.people.xsd.visura package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VisuraDettaglioPratica_QNAME = new QName("http://myPage.init.it/VisuraTypes", "VisuraDettaglioPratica");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.people.xsd.visura
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParametroType }
     * 
     */
    public ParametroType createParametroType() {
        return new ParametroType();
    }

    /**
     * Create an instance of {@link AnagrafeType }
     * 
     */
    public AnagrafeType createAnagrafeType() {
        return new AnagrafeType();
    }

    /**
     * Create an instance of {@link SportelloType }
     * 
     */
    public SportelloType createSportelloType() {
        return new SportelloType();
    }

    /**
     * Create an instance of {@link AltriSoggettiType }
     * 
     */
    public AltriSoggettiType createAltriSoggettiType() {
        return new AltriSoggettiType();
    }

    /**
     * Create an instance of {@link SchedaType }
     * 
     */
    public SchedaType createSchedaType() {
        return new SchedaType();
    }

    /**
     * Create an instance of {@link IscrizioneRegistroType }
     * 
     */
    public IscrizioneRegistroType createIscrizioneRegistroType() {
        return new IscrizioneRegistroType();
    }

    /**
     * Create an instance of {@link DocumentiType }
     * 
     */
    public DocumentiType createDocumentiType() {
        return new DocumentiType();
    }

    /**
     * Create an instance of {@link VisuraDettaglioPraticaType }
     * 
     */
    public VisuraDettaglioPraticaType createVisuraDettaglioPraticaType() {
        return new VisuraDettaglioPraticaType();
    }

    /**
     * Create an instance of {@link InterventoType }
     * 
     */
    public InterventoType createInterventoType() {
        return new InterventoType();
    }

    /**
     * Create an instance of {@link RiferimentoCatastaleType }
     * 
     */
    public RiferimentoCatastaleType createRiferimentoCatastaleType() {
        return new RiferimentoCatastaleType();
    }

    /**
     * Create an instance of {@link RiferimentiAttivitaType }
     * 
     */
    public RiferimentiAttivitaType createRiferimentiAttivitaType() {
        return new RiferimentiAttivitaType();
    }

    /**
     * Create an instance of {@link ComuneType }
     * 
     */
    public ComuneType createComuneType() {
        return new ComuneType();
    }

    /**
     * Create an instance of {@link TipoAttivitaType }
     * 
     */
    public TipoAttivitaType createTipoAttivitaType() {
        return new TipoAttivitaType();
    }

    /**
     * Create an instance of {@link DirezioneType }
     * 
     */
    public DirezioneType createDirezioneType() {
        return new DirezioneType();
    }

    /**
     * Create an instance of {@link RiferimentiPraticaType }
     * 
     */
    public RiferimentiPraticaType createRiferimentiPraticaType() {
        return new RiferimentiPraticaType();
    }

    /**
     * Create an instance of {@link LocalizzazioneType }
     * 
     */
    public LocalizzazioneType createLocalizzazioneType() {
        return new LocalizzazioneType();
    }

    /**
     * Create an instance of {@link RuoloType }
     * 
     */
    public RuoloType createRuoloType() {
        return new RuoloType();
    }

    /**
     * Create an instance of {@link RiferimentiAllegatoType }
     * 
     */
    public RiferimentiAllegatoType createRiferimentiAllegatoType() {
        return new RiferimentiAllegatoType();
    }

    /**
     * Create an instance of {@link ProcedimentoType }
     * 
     */
    public ProcedimentoType createProcedimentoType() {
        return new ProcedimentoType();
    }

    /**
     * Create an instance of {@link ErroreType }
     * 
     */
    public ErroreType createErroreType() {
        return new ErroreType();
    }

    /**
     * Create an instance of {@link AllegatoBinarioType }
     * 
     */
    public AllegatoBinarioType createAllegatoBinarioType() {
        return new AllegatoBinarioType();
    }

    /**
     * Create an instance of {@link DettaglioPraticaType }
     * 
     */
    public DettaglioPraticaType createDettaglioPraticaType() {
        return new DettaglioPraticaType();
    }

    /**
     * Create an instance of {@link LocalizzazioneNelComuneType }
     * 
     */
    public LocalizzazioneNelComuneType createLocalizzazioneNelComuneType() {
        return new LocalizzazioneNelComuneType();
    }

    /**
     * Create an instance of {@link PersonaFisicaType }
     * 
     */
    public PersonaFisicaType createPersonaFisicaType() {
        return new PersonaFisicaType();
    }

    /**
     * Create an instance of {@link PersonaGiuridicaType }
     * 
     */
    public PersonaGiuridicaType createPersonaGiuridicaType() {
        return new PersonaGiuridicaType();
    }

    /**
     * Create an instance of {@link DettaglioAttivitaType }
     * 
     */
    public DettaglioAttivitaType createDettaglioAttivitaType() {
        return new DettaglioAttivitaType();
    }

    /**
     * Create an instance of {@link AllegatiType }
     * 
     */
    public AllegatiType createAllegatiType() {
        return new AllegatiType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VisuraDettaglioPraticaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://myPage.init.it/VisuraTypes", name = "VisuraDettaglioPratica")
    public JAXBElement<VisuraDettaglioPraticaType> createVisuraDettaglioPratica(VisuraDettaglioPraticaType value) {
        return new JAXBElement<VisuraDettaglioPraticaType>(_VisuraDettaglioPratica_QNAME, VisuraDettaglioPraticaType.class, null, value);
    }

}
