
package it.wego.cross.webservices.mypage.syncronizer;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://mypagesynchronizer.wego.it/")
public class Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private it.wego.cross.webservices.mypage.syncronizer.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception(String message, it.wego.cross.webservices.mypage.syncronizer.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception(String message, it.wego.cross.webservices.mypage.syncronizer.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.wego.cross.webservices.mypage.syncronizer.Exception
     */
    public it.wego.cross.webservices.mypage.syncronizer.Exception getFaultInfo() {
        return faultInfo;
    }

}
