//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.28 at 06:31:28 PM CET 
//


package it.wego.cross.client.xml.ricercaprotocollo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:eGrammata:RisultatoRicerca.xsd}EstremiReg"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "estremiReg"
})
public class RegSecondaria {

    @XmlElement(name = "EstremiReg", required = true)
    protected EstremiReg estremiReg;

    /**
     * Gets the value of the estremiReg property.
     * 
     * @return
     *     possible object is
     *     {@link EstremiReg }
     *     
     */
    public EstremiReg getEstremiReg() {
        return estremiReg;
    }

    /**
     * Sets the value of the estremiReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstremiReg }
     *     
     */
    public void setEstremiReg(EstremiReg value) {
        this.estremiReg = value;
    }

}
