//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.27 at 06:54:59 PM CET 
//


package it.wego.people.simpledesk.processdata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}campi"/>
 *         &lt;element ref="{}codice"/>
 *         &lt;element ref="{}complete"/>
 *         &lt;element ref="{}descrizione"/>
 *         &lt;element ref="{}firstRowCampoMultiplo"/>
 *         &lt;element ref="{}href"/>
 *         &lt;element ref="{}html"/>
 *         &lt;element ref="{}htmlEditable"/>
 *         &lt;element ref="{}lastRowCampoMultiplo"/>
 *         &lt;element ref="{}link"/>
 *         &lt;element ref="{}numSezioniMultiple"/>
 *         &lt;element ref="{}ordinamento"/>
 *         &lt;element ref="{}ordinamentoIntervento"/>
 *         &lt;element ref="{}piedeHref"/>
 *         &lt;element ref="{}rowCount"/>
 *         &lt;element ref="{}tdCount"/>
 *         &lt;element ref="{}titolo"/>
 *         &lt;element ref="{}visible"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "value")
public class Href {

    @XmlElement(required = true)
    protected CampiWrapper campi;
    @XmlElement(required = true)
    protected String codice;
    protected boolean complete;
    @XmlElement(required = true)
    protected String descrizione;
    @XmlElement(required = true)
    protected Integer firstRowCampoMultiplo;
    @XmlElement(required = true)
    protected String href;
    @XmlElement(required = true)
    protected String html;
    @XmlElement(required = true)
    protected String htmlEditable;
    @XmlElement(required = true)
    protected Integer lastRowCampoMultiplo;
    @XmlElement(required = true)
    protected String link;
    @XmlElement(required = true)
    protected Integer numSezioniMultiple;
    @XmlElement(required = true)
    protected Integer ordinamento;
    @XmlElement(required = true)
    protected Integer ordinamentoIntervento;
    @XmlElement(required = true)
    protected String piedeHref;
    @XmlElement(required = true)
    protected Integer rowCount;
    @XmlElement(required = true)
    protected Integer tdCount;
    @XmlElement(required = true)
    protected String titolo;
    protected boolean visible;

    /**
     * Gets the value of the campi property.
     * 
     * @return
     *     possible object is
     *     {@link Campi }
     *     
     */
    public CampiWrapper getCampi() {
        return campi;
    }

    /**
     * Sets the value of the campi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Campi }
     *     
     */
    public void setCampi(CampiWrapper value) {
        this.campi = value;
    }

    /**
     * Gets the value of the codice property.
     * 
     * @return
     *     possible object is
     *     {@link Codice }
     *     
     */
    public String getCodice() {
        return codice;
    }

    /**
     * Sets the value of the codice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Codice }
     *     
     */
    public void setCodice(String value) {
        this.codice = value;
    }

    /**
     * Gets the value of the complete property.
     * 
     */
    public boolean isComplete() {
        return complete;
    }

    /**
     * Sets the value of the complete property.
     * 
     */
    public void setComplete(boolean value) {
        this.complete = value;
    }

    /**
     * Gets the value of the descrizione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * Sets the value of the descrizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrizione(String value) {
        this.descrizione = value;
    }

    /**
     * Gets the value of the firstRowCampoMultiplo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFirstRowCampoMultiplo() {
        return firstRowCampoMultiplo;
    }

    /**
     * Sets the value of the firstRowCampoMultiplo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFirstRowCampoMultiplo(Integer value) {
        this.firstRowCampoMultiplo = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the html property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtml() {
        return html;
    }

    /**
     * Sets the value of the html property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtml(String value) {
        this.html = value;
    }

    /**
     * Gets the value of the htmlEditable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtmlEditable() {
        return htmlEditable;
    }

    /**
     * Sets the value of the htmlEditable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtmlEditable(String value) {
        this.htmlEditable = value;
    }

    /**
     * Gets the value of the lastRowCampoMultiplo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLastRowCampoMultiplo() {
        return lastRowCampoMultiplo;
    }

    /**
     * Sets the value of the lastRowCampoMultiplo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLastRowCampoMultiplo(Integer value) {
        this.lastRowCampoMultiplo = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the numSezioniMultiple property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumSezioniMultiple() {
        return numSezioniMultiple;
    }

    /**
     * Sets the value of the numSezioniMultiple property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumSezioniMultiple(Integer value) {
        this.numSezioniMultiple = value;
    }

    /**
     * Gets the value of the ordinamento property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrdinamento() {
        return ordinamento;
    }

    /**
     * Sets the value of the ordinamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrdinamento(Integer value) {
        this.ordinamento = value;
    }

    /**
     * Gets the value of the ordinamentoIntervento property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrdinamentoIntervento() {
        return ordinamentoIntervento;
    }

    /**
     * Sets the value of the ordinamentoIntervento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrdinamentoIntervento(Integer value) {
        this.ordinamentoIntervento = value;
    }

    /**
     * Gets the value of the piedeHref property.
     * 
     * @return
     *     possible object is
     *     {@link PiedeHref }
     *     
     */
    public String getPiedeHref() {
        return piedeHref;
    }

    /**
     * Sets the value of the piedeHref property.
     * 
     * @param value
     *     allowed object is
     *     {@link PiedeHref }
     *     
     */
    public void setPiedeHref(String value) {
        this.piedeHref = value;
    }

    /**
     * Gets the value of the rowCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRowCount() {
        return rowCount;
    }

    /**
     * Sets the value of the rowCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRowCount(Integer value) {
        this.rowCount = value;
    }

    /**
     * Gets the value of the tdCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTdCount() {
        return tdCount;
    }

    /**
     * Sets the value of the tdCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTdCount(Integer value) {
        this.tdCount = value;
    }

    /**
     * Gets the value of the titolo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitolo() {
        return titolo;
    }

    /**
     * Sets the value of the titolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitolo(String value) {
        this.titolo = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     */
    public boolean isVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     */
    public void setVisible(boolean value) {
        this.visible = value;
    }

}
