package it.wego.cross.genova.toponomastica.client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebServiceClient(name = "elencoVie", targetNamespace = "http://webservice.backend.people.it/", wsdlLocation = "http://ws.si-france.fr/elencoVie/elencoVie.asmx?wsdl")
public class ElencoVie
        extends Service {

    private final static URL ELENCOVIE_WSDL_LOCATION;
    private final static WebServiceException ELENCOVIE_EXCEPTION;
    private final static QName ELENCOVIE_QNAME = new QName("http://webservice.backend.people.it/", "elencoVie");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws.si-france.fr/elencoVie/elencoVie.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ELENCOVIE_WSDL_LOCATION = url;
        ELENCOVIE_EXCEPTION = e;
    }

    public ElencoVie() {
        super(__getWsdlLocation(), ELENCOVIE_QNAME);
    }

    public ElencoVie(URL wsdlLocation) {
        super(wsdlLocation, ELENCOVIE_QNAME);
    }

    public ElencoVie(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return returns ElencoVieSoap
     */
    @WebEndpoint(name = "elencoVieSoap")
    public ElencoVieSoap getElencoVieSoap() {
        return super.getPort(new QName("http://webservice.backend.people.it/", "elencoVieSoap"), ElencoVieSoap.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in
     * the <code>features</code> parameter will have their default values.
     * @return returns ElencoVieSoap
     */
    @WebEndpoint(name = "elencoVieSoap")
    public ElencoVieSoap getElencoVieSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.backend.people.it/", "elencoVieSoap"), ElencoVieSoap.class, features);
    }

    /**
     *
     * @return returns ElencoVieSoap
     */
    @WebEndpoint(name = "elencoVieSoap12")
    public ElencoVieSoap getElencoVieSoap12() {
        return super.getPort(new QName("http://webservice.backend.people.it/", "elencoVieSoap12"), ElencoVieSoap.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in
     * the <code>features</code> parameter will have their default values.
     * @return returns ElencoVieSoap
     */
    @WebEndpoint(name = "elencoVieSoap12")
    public ElencoVieSoap getElencoVieSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.backend.people.it/", "elencoVieSoap12"), ElencoVieSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ELENCOVIE_EXCEPTION != null) {
            throw ELENCOVIE_EXCEPTION;
        }
        return ELENCOVIE_WSDL_LOCATION;
    }
}
