//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.02 at 03:51:49 PM CET 
//


package it.gov.impresainungiorno.schema.suap.ricevuta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import it.gov.impresainungiorno.schema.base.Anagrafica;
import it.gov.impresainungiorno.schema.suap.pratica.AnagraficaImpresa;
import it.gov.impresainungiorno.schema.suap.pratica.EstremiDichiarante;
import it.gov.impresainungiorno.schema.suap.pratica.EstremiEnte;
import it.gov.impresainungiorno.schema.suap.pratica.OggettoComunicazione;
import it.gov.impresainungiorno.schema.suap.pratica.ProtocolloSUAP;


/**
 * <p>Java class for IntestazioneRicevuta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntestazioneRicevuta">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ufficio-ricevente" type="{http://www.impresainungiorno.gov.it/schema/suap/pratica}EstremiEnte"/>
 *         &lt;element name="impresa" type="{http://www.impresainungiorno.gov.it/schema/suap/pratica}AnagraficaImpresa"/>
 *         &lt;element name="oggetto-comunicazione" type="{http://www.impresainungiorno.gov.it/schema/suap/pratica}OggettoComunicazione"/>
 *         &lt;element name="dichiarante" type="{http://www.impresainungiorno.gov.it/schema/suap/pratica}EstremiDichiarante"/>
 *         &lt;element name="responsabile" type="{http://www.impresainungiorno.gov.it/schema/base}Anagrafica"/>
 *         &lt;element name="protocollo" type="{http://www.impresainungiorno.gov.it/schema/suap/pratica}ProtocolloSUAP"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntestazioneRicevuta", propOrder = {
    "ufficioRicevente",
    "impresa",
    "oggettoComunicazione",
    "dichiarante",
    "responsabile",
    "protocollo"
})
public class IntestazioneRicevuta {

    @XmlElement(name = "ufficio-ricevente", required = true)
    protected EstremiEnte ufficioRicevente;
    @XmlElement(required = true)
    protected AnagraficaImpresa impresa;
    @XmlElement(name = "oggetto-comunicazione", required = true)
    protected OggettoComunicazione oggettoComunicazione;
    @XmlElement(required = true)
    protected EstremiDichiarante dichiarante;
    @XmlElement(required = true)
    protected Anagrafica responsabile;
    @XmlElement(required = true)
    protected ProtocolloSUAP protocollo;

    /**
     * Gets the value of the ufficioRicevente property.
     * 
     * @return
     *     possible object is
     *     {@link EstremiEnte }
     *     
     */
    public EstremiEnte getUfficioRicevente() {
        return ufficioRicevente;
    }

    /**
     * Sets the value of the ufficioRicevente property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstremiEnte }
     *     
     */
    public void setUfficioRicevente(EstremiEnte value) {
        this.ufficioRicevente = value;
    }

    /**
     * Gets the value of the impresa property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaImpresa }
     *     
     */
    public AnagraficaImpresa getImpresa() {
        return impresa;
    }

    /**
     * Sets the value of the impresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaImpresa }
     *     
     */
    public void setImpresa(AnagraficaImpresa value) {
        this.impresa = value;
    }

    /**
     * Gets the value of the oggettoComunicazione property.
     * 
     * @return
     *     possible object is
     *     {@link OggettoComunicazione }
     *     
     */
    public OggettoComunicazione getOggettoComunicazione() {
        return oggettoComunicazione;
    }

    /**
     * Sets the value of the oggettoComunicazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link OggettoComunicazione }
     *     
     */
    public void setOggettoComunicazione(OggettoComunicazione value) {
        this.oggettoComunicazione = value;
    }

    /**
     * Gets the value of the dichiarante property.
     * 
     * @return
     *     possible object is
     *     {@link EstremiDichiarante }
     *     
     */
    public EstremiDichiarante getDichiarante() {
        return dichiarante;
    }

    /**
     * Sets the value of the dichiarante property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstremiDichiarante }
     *     
     */
    public void setDichiarante(EstremiDichiarante value) {
        this.dichiarante = value;
    }

    /**
     * Gets the value of the responsabile property.
     * 
     * @return
     *     possible object is
     *     {@link Anagrafica }
     *     
     */
    public Anagrafica getResponsabile() {
        return responsabile;
    }

    /**
     * Sets the value of the responsabile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anagrafica }
     *     
     */
    public void setResponsabile(Anagrafica value) {
        this.responsabile = value;
    }

    /**
     * Gets the value of the protocollo property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolloSUAP }
     *     
     */
    public ProtocolloSUAP getProtocollo() {
        return protocollo;
    }

    /**
     * Sets the value of the protocollo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolloSUAP }
     *     
     */
    public void setProtocollo(ProtocolloSUAP value) {
        this.protocollo = value;
    }

}
