//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.09 at 06:52:57 PM CET 
//


package it.wego.cross.xsd.reporter.documentoutputtype;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.wego.xsd.reporter.documentoutputtype package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.wego.xsd.reporter.documentoutputtype
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OutputTypeRoot }
     * 
     */
    public OutputTypeRoot createOutputTypeRoot() {
        return new OutputTypeRoot();
    }

    /**
     * Create an instance of {@link OutputTypeRoot.OutputPath }
     * 
     */
    public OutputTypeRoot.OutputPath createOutputTypeRootOutputPath() {
        return new OutputTypeRoot.OutputPath();
    }

}
