package it.wego.cross.webservices.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-15T16:48:22.699+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://webservice.backend.people.it/", name = "PeoplePratiche")
@XmlSeeAlso({ObjectFactory.class})
public interface PeoplePraticheService {

    @WebResult(name = "processReturn", targetNamespace = "http://webservice.backend.people.it/")
    @RequestWrapper(localName = "process", targetNamespace = "http://webservice.backend.people.it/", className = "it.wego.cross.webservices.cxf.Process")
    @WebMethod(action = "process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://webservice.backend.people.it/", className = "it.wego.cross.webservices.cxf.ProcessResponse")
    public java.lang.String process(
        @WebParam(name = "data", targetNamespace = "http://webservice.backend.people.it/")
        java.lang.String data
    );
}
