cd BEService/
mvn tomcat6:redeploy
cd ../Dbm/
mvn tomcat6:redeploy
cd ../idp_people
mvn tomcat6:redeploy
cd ../IdpPeopleAdmin
mvn tomcat6:redeploy
cd ../PeopleConsole
mvn tomcat6:redeploy
cd ../scauth
mvn tomcat6:redeploy
cd ../ws_accr_121
mvn tomcat6:redeploy
cd ../ws_regauth
mvn tomcat6:redeploy
cd ../sirac
mvn tomcat6:redeploy
