cd BEService/
mvn tomcat7:redeploy
cd ../Dbm/
mvn tomcat7:redeploy
cd ../idp_people
mvn tomcat7:redeploy
cd ../IdpPeopleAdmin
mvn tomcat7:redeploy
cd ../PeopleConsole
mvn tomcat7:redeploy
cd ../scauth
mvn tomcat7:redeploy
cd ../ws_accr_121
mvn tomcat7:redeploy
cd ../ws_regauth
mvn tomcat7:redeploy
cd ../sirac
mvn tomcat7:redeploy
