package it.wego.cross.avbari.linksmt.protocollo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-03-19T15:16:32.357+01:00
 * Generated source version: 2.3.9
 * 
 */
@WebService(targetNamespace = "http://server.ws.protocollo.linksmt.it/", name = "ProtocolloServer")
@XmlSeeAlso({ObjectFactory.class})
public interface ProtocolloServer {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "inoltraProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.InoltraProtocollo")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "inoltraProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.InoltraProtocolloResponse")
    public it.wego.cross.avbari.linksmt.protocollo.InoltraProtocolloResponse.Return inoltraProtocollo(
        @WebParam(name = "inoltroProtocolloRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.InoltraProtocollo.InoltroProtocolloRequest inoltroProtocolloRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "completamentoProtocolloProvvisorio", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.CompletamentoProtocolloProvvisorio")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "completamentoProtocolloProvvisorioResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.CompletamentoProtocolloProvvisorioResponse")
    public it.wego.cross.avbari.linksmt.protocollo.CompletamentoProtocolloProvvisorioResponse.Return completamentoProtocolloProvvisorio(
        @WebParam(name = "protocolloDaCompletareRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.CompletamentoProtocolloProvvisorio.ProtocolloDaCompletareRequest protocolloDaCompletareRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "richiestaProtocolloUscitaFasc", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloUscitaFasc")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "richiestaProtocolloUscitaFascResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloUscitaFascResponse")
    public it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloUscitaFascResponse.Return richiestaProtocolloUscitaFasc(
        @WebParam(name = "protocolloUscitaFascRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloUscitaFasc.ProtocolloUscitaFascRequest protocolloUscitaFascRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "richiestaProtocolloProvvisorio", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloProvvisorio")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "richiestaProtocolloProvvisorioResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloProvvisorioResponse")
    public it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloProvvisorioResponse.Return richiestaProtocolloProvvisorio(
        @WebParam(name = "protocolloProvvisorioRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloProvvisorio.ProtocolloProvvisorioRequest protocolloProvvisorioRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "richiestaProtocolloUscita", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloUscita")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "richiestaProtocolloUscitaResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloUscitaResponse")
    public it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloUscitaResponse.Return richiestaProtocolloUscita(
        @WebParam(name = "protocolloUscitaRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloUscita.ProtocolloUscitaRequest protocolloUscitaRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "richiestaProtocolloFasc", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloFasc")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "richiestaProtocolloFascResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloFascResponse")
    public it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloFascResponse.Return richiestaProtocolloFasc(
        @WebParam(name = "protocolloFascRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloFasc.ProtocolloFascRequest protocolloFascRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllegato", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.GetAllegato")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "getAllegatoResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.GetAllegatoResponse")
    public it.wego.cross.avbari.linksmt.protocollo.GetAllegatoResponse.Return getAllegato(
        @WebParam(name = "dettaglioAllegatoRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.GetAllegato.DettaglioAllegatoRequest dettaglioAllegatoRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addAllegatura", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.AddAllegatura")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "addAllegaturaResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.AddAllegaturaResponse")
    public it.wego.cross.avbari.linksmt.protocollo.AddAllegaturaResponse.Return addAllegatura(
        @WebParam(name = "allegaturaRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.AddAllegatura.AllegaturaRequest allegaturaRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDestinatariProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.GetDestinatariProtocollo")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "getDestinatariProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.GetDestinatariProtocolloResponse")
    public it.wego.cross.avbari.linksmt.protocollo.GetDestinatariProtocolloResponse.Return getDestinatariProtocollo(
        @WebParam(name = "destinatarioProtocolloRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.GetDestinatariProtocollo.DestinatarioProtocolloRequest destinatarioProtocolloRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "richiestaProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocollo")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "richiestaProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloResponse")
    public it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocolloResponse.Return richiestaProtocollo(
        @WebParam(name = "protocolloRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.RichiestaProtocollo.ProtocolloRequest protocolloRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.GetProtocollo")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "getProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.GetProtocolloResponse")
    public it.wego.cross.avbari.linksmt.protocollo.GetProtocolloResponse.Return getProtocollo(
        @WebParam(name = "protocolloInformazioniRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.GetProtocollo.ProtocolloInformazioniRequest protocolloInformazioniRequest
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMittenteProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.GetMittenteProtocollo")
    @WebMethod(action = "return")
    @ResponseWrapper(localName = "getMittenteProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.wego.cross.avbari.linksmt.protocollo.GetMittenteProtocolloResponse")
    public it.wego.cross.avbari.linksmt.protocollo.GetMittenteProtocolloResponse.Return getMittenteProtocollo(
        @WebParam(name = "mittenteProtocolloRequest", targetNamespace = "")
        it.wego.cross.avbari.linksmt.protocollo.GetMittenteProtocollo.MittenteProtocolloRequest mittenteProtocolloRequest
    );
}
