//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 09:44:53 AM CET 
//


package it.gov.impresainungiorno.schema.suap.riepilogo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import it.gov.impresainungiorno.schema.base.CodiceREA;
import it.gov.impresainungiorno.schema.base.FormaGiuridica;


/**
 * 
 *             Questo elemento contiene i dati identificativi di un'impresa
 *         
 * 
 * <p>Java class for AnagraficaImpresa complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnagraficaImpresa">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="forma-giuridica" type="{http://www.impresainungiorno.gov.it/schema/base}FormaGiuridica" minOccurs="0"/>
 *         &lt;element name="ragione-sociale" type="{http://www.impresainungiorno.gov.it/schema/base}Stringa"/>
 *         &lt;element name="codice-fiscale" type="{http://www.impresainungiorno.gov.it/schema/base}CodiceFiscale"/>
 *         &lt;element name="partita-iva" type="{http://www.impresainungiorno.gov.it/schema/base}PartitaIVA" minOccurs="0"/>
 *         &lt;element name="codice-REA" type="{http://www.impresainungiorno.gov.it/schema/base}CodiceREA"/>
 *         &lt;element name="domicilio-elettronico" type="{http://www.impresainungiorno.gov.it/schema/base}EMailIndirizzo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnagraficaImpresa", propOrder = {
    "formaGiuridica",
    "ragioneSociale",
    "codiceFiscale",
    "partitaIva",
    "codiceREA",
    "domicilioElettronico"
})
public class AnagraficaImpresa {

    @XmlElement(name = "forma-giuridica")
    protected FormaGiuridica formaGiuridica;
    @XmlElement(name = "ragione-sociale", required = true)
    protected String ragioneSociale;
    @XmlElement(name = "codice-fiscale", required = true)
    protected String codiceFiscale;
    @XmlElement(name = "partita-iva")
    protected String partitaIva;
    @XmlElement(name = "codice-REA", required = true)
    protected CodiceREA codiceREA;
    @XmlElement(name = "domicilio-elettronico")
    protected String domicilioElettronico;

    /**
     * Gets the value of the formaGiuridica property.
     * 
     * @return
     *     possible object is
     *     {@link FormaGiuridica }
     *     
     */
    public FormaGiuridica getFormaGiuridica() {
        return formaGiuridica;
    }

    /**
     * Sets the value of the formaGiuridica property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormaGiuridica }
     *     
     */
    public void setFormaGiuridica(FormaGiuridica value) {
        this.formaGiuridica = value;
    }

    /**
     * Gets the value of the ragioneSociale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRagioneSociale() {
        return ragioneSociale;
    }

    /**
     * Sets the value of the ragioneSociale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRagioneSociale(String value) {
        this.ragioneSociale = value;
    }

    /**
     * Gets the value of the codiceFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    /**
     * Sets the value of the codiceFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscale(String value) {
        this.codiceFiscale = value;
    }

    /**
     * Gets the value of the partitaIva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartitaIva() {
        return partitaIva;
    }

    /**
     * Sets the value of the partitaIva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartitaIva(String value) {
        this.partitaIva = value;
    }

    /**
     * Gets the value of the codiceREA property.
     * 
     * @return
     *     possible object is
     *     {@link CodiceREA }
     *     
     */
    public CodiceREA getCodiceREA() {
        return codiceREA;
    }

    /**
     * Sets the value of the codiceREA property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodiceREA }
     *     
     */
    public void setCodiceREA(CodiceREA value) {
        this.codiceREA = value;
    }

    /**
     * Il domicilio elettronico viene restituito dal Registro Imprese nel caso in cui l'impresa chieda nella pratica ComUnica l'attribuzione della PEC
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomicilioElettronico() {
        return domicilioElettronico;
    }

    /**
     * Il domicilio elettronico viene restituito dal Registro Imprese nel caso in cui l'impresa chieda nella pratica ComUnica l'attribuzione della PEC
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomicilioElettronico(String value) {
        this.domicilioElettronico = value;
    }

}
