//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.22 at 09:44:53 AM CET 
//


package it.gov.impresainungiorno.schema.suap.riepilogo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import it.gov.impresainungiorno.schema.suap.pratica.EstremiSuap;
import it.gov.impresainungiorno.schema.suap.pratica.ProtocolloRI;


/**
 * <p>Java class for SuapRI complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuapRI">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="suap" type="{http://www.impresainungiorno.gov.it/schema/suap/pratica}EstremiSuap"/>
 *         &lt;element name="codice-pratica" type="{http://www.impresainungiorno.gov.it/schema/suap/riepilogo}CodicePraticaComUnica"/>
 *         &lt;element name="impresa" type="{http://www.impresainungiorno.gov.it/schema/suap/riepilogo}AnagraficaImpresa"/>
 *         &lt;element name="protocollo-ri" type="{http://www.impresainungiorno.gov.it/schema/suap/pratica}ProtocolloRI"/>
 *         &lt;element name="allegato" type="{http://www.impresainungiorno.gov.it/schema/suap/riepilogo}AllegatoPraticaSUAP"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuapRI", propOrder = {
    "suap",
    "codicePratica",
    "impresa",
    "protocolloRi",
    "allegato"
})
public class SuapRI {

    @XmlElement(required = true)
    protected EstremiSuap suap;
    @XmlElement(name = "codice-pratica", required = true)
    protected String codicePratica;
    @XmlElement(required = true)
    protected AnagraficaImpresa impresa;
    @XmlElement(name = "protocollo-ri", required = true)
    protected ProtocolloRI protocolloRi;
    @XmlElement(required = true)
    protected AllegatoPraticaSUAP allegato;

    /**
     * Gets the value of the suap property.
     * 
     * @return
     *     possible object is
     *     {@link EstremiSuap }
     *     
     */
    public EstremiSuap getSuap() {
        return suap;
    }

    /**
     * Sets the value of the suap property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstremiSuap }
     *     
     */
    public void setSuap(EstremiSuap value) {
        this.suap = value;
    }

    /**
     * E' il codice pratica ComUnica che conteneva la SICA contestuale che vieni inviata al SUAP competente
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodicePratica() {
        return codicePratica;
    }

    /**
     * E' il codice pratica ComUnica che conteneva la SICA contestuale che vieni inviata al SUAP competente
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodicePratica(String value) {
        this.codicePratica = value;
    }

    /**
     * Questo elemento contiene i dati identificativi di un'impresa
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaImpresa }
     *     
     */
    public AnagraficaImpresa getImpresa() {
        return impresa;
    }

    /**
     * Questo elemento contiene i dati identificativi di un'impresa
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaImpresa }
     *     
     */
    public void setImpresa(AnagraficaImpresa value) {
        this.impresa = value;
    }

    /**
     * Gets the value of the protocolloRi property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolloRI }
     *     
     */
    public ProtocolloRI getProtocolloRi() {
        return protocolloRi;
    }

    /**
     * Sets the value of the protocolloRi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolloRI }
     *     
     */
    public void setProtocolloRi(ProtocolloRI value) {
        this.protocolloRi = value;
    }

    /**
     * Gets the value of the allegato property.
     * 
     * @return
     *     possible object is
     *     {@link AllegatoPraticaSUAP }
     *     
     */
    public AllegatoPraticaSUAP getAllegato() {
        return allegato;
    }

    /**
     * Sets the value of the allegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllegatoPraticaSUAP }
     *     
     */
    public void setAllegato(AllegatoPraticaSUAP value) {
        this.allegato = value;
    }

}
