
package it.gov.impresainungiorno.suap.scrivania;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import it.gov.impresainungiorno.schema.suap.ente.CooperazioneSUAPEnte;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PddServiceEnte", targetNamespace = "http://www.impresainungiorno.gov.it/suap/scrivania")
@XmlSeeAlso({
    it.gov.impresainungiorno.schema.suap.pratica.ObjectFactory.class,
    it.gov.impresainungiorno.schema.base.ObjectFactory.class,
    it.gov.impresainungiorno.schema.suap.ente.ObjectFactory.class,
    it.gov.impresainungiorno.suap.scrivania.ObjectFactory.class
})
@SOAPBinding(style = Style.DOCUMENT)
public interface PddServiceEnte {


    /**
     * 
     * @param cooperazioneSUAPEnte
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "inviaSUAPEnte")
    //@XmlAttachmentRef
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inviaSUAPEnte", targetNamespace = "http://www.impresainungiorno.gov.it/suap/scrivania", className = "it.gov.impresainungiorno.suap.scrivania.InviaSUAPEnte")
    @ResponseWrapper(localName = "inviaSUAPEnteResponse", targetNamespace = "http://www.impresainungiorno.gov.it/suap/scrivania", className = "it.gov.impresainungiorno.suap.scrivania.InviaSUAPEnteResponse")
    public String inviaSUAPEnte(
        @WebParam(name = "CooperazioneSUAPEnte", targetNamespace = "")
        CooperazioneSUAPEnte cooperazioneSUAPEnte);

}
