package it.linksmt.protocollo.ws.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2020-11-06T09:27:28.765+01:00
 * Generated source version: 2.3.9
 * 
 */
@WebService(targetNamespace = "http://server.ws.protocollo.linksmt.it/", name = "ProtocolloServer")
@XmlSeeAlso({ObjectFactory.class, it.linksmt.protocollo.richiestasoap.ObjectFactory.class})
public interface ProtocolloServer {

    @WebMethod(action = "return")
    @RequestWrapper(localName = "richiestaProtocolloUscitaFasc", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.RichiestaProtocolloUscitaFasc")
    @ResponseWrapper(localName = "richiestaProtocolloUscitaFascResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.RichiestaProtocolloUscitaFascResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.RichiestaProtocolloUscitaFascResponse.Return richiestaProtocolloUscitaFasc(
        @WebParam(name = "protocolloUscitaFascRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.RichiestaProtocolloUscitaFasc.ProtocolloUscitaFascRequest protocolloUscitaFascRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "addAllegatura", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.AddAllegatura")
    @ResponseWrapper(localName = "addAllegaturaResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.AddAllegaturaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.AddAllegaturaResponse.Return addAllegatura(
        @WebParam(name = "allegaturaRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.AddAllegatura.AllegaturaRequest allegaturaRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "richiestaProtocolloProvvisorio", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.RichiestaProtocolloProvvisorio")
    @ResponseWrapper(localName = "richiestaProtocolloProvvisorioResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.RichiestaProtocolloProvvisorioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.RichiestaProtocolloProvvisorioResponse.Return richiestaProtocolloProvvisorio(
        @WebParam(name = "protocolloProvvisorioRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.RichiestaProtocolloProvvisorio.ProtocolloProvvisorioRequest protocolloProvvisorioRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "getDestinatariProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.GetDestinatariProtocollo")
    @ResponseWrapper(localName = "getDestinatariProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.GetDestinatariProtocolloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.GetDestinatariProtocolloResponse.Return getDestinatariProtocollo(
        @WebParam(name = "destinatarioProtocolloRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.GetDestinatariProtocollo.DestinatarioProtocolloRequest destinatarioProtocolloRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "getMittenteProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.GetMittenteProtocollo")
    @ResponseWrapper(localName = "getMittenteProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.GetMittenteProtocolloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.GetMittenteProtocolloResponse.Return getMittenteProtocollo(
        @WebParam(name = "mittenteProtocolloRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.GetMittenteProtocollo.MittenteProtocolloRequest mittenteProtocolloRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "richiestaProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.RichiestaProtocollo")
    @ResponseWrapper(localName = "richiestaProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.RichiestaProtocolloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.RichiestaProtocolloResponse.Return richiestaProtocollo(
        @WebParam(name = "protocolloRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.RichiestaProtocollo.ProtocolloRequest protocolloRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "inoltraProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.InoltraProtocollo")
    @ResponseWrapper(localName = "inoltraProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.InoltraProtocolloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.InoltraProtocolloResponse.Return inoltraProtocollo(
        @WebParam(name = "inoltroProtocolloRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.InoltraProtocollo.InoltroProtocolloRequest inoltroProtocolloRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "getAllegato", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.GetAllegato")
    @ResponseWrapper(localName = "getAllegatoResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.GetAllegatoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.GetAllegatoResponse.Return getAllegato(
        @WebParam(name = "dettaglioAllegatoRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.GetAllegato.DettaglioAllegatoRequest dettaglioAllegatoRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "richiestaProtocolloFasc", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.RichiestaProtocolloFasc")
    @ResponseWrapper(localName = "richiestaProtocolloFascResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.RichiestaProtocolloFascResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.RichiestaProtocolloFascResponse.Return richiestaProtocolloFasc(
        @WebParam(name = "protocolloFascRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.RichiestaProtocolloFasc.ProtocolloFascRequest protocolloFascRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "completamentoProtocolloProvvisorio", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.CompletamentoProtocolloProvvisorio")
    @ResponseWrapper(localName = "completamentoProtocolloProvvisorioResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.CompletamentoProtocolloProvvisorioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.CompletamentoProtocolloProvvisorioResponse.Return completamentoProtocolloProvvisorio(
        @WebParam(name = "protocolloDaCompletareRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.CompletamentoProtocolloProvvisorio.ProtocolloDaCompletareRequest protocolloDaCompletareRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "getProtocollo", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.GetProtocollo")
    @ResponseWrapper(localName = "getProtocolloResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.GetProtocolloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.GetProtocolloResponse.Return getProtocollo(
        @WebParam(name = "protocolloInformazioniRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.GetProtocollo.ProtocolloInformazioniRequest protocolloInformazioniRequest
    );

    @WebMethod(action = "return")
    @RequestWrapper(localName = "richiestaProtocolloUscita", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.RichiestaProtocolloUscita")
    @ResponseWrapper(localName = "richiestaProtocolloUscitaResponse", targetNamespace = "http://server.ws.protocollo.linksmt.it/", className = "it.linksmt.protocollo.ws.server.RichiestaProtocolloUscitaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.linksmt.protocollo.ws.server.RichiestaProtocolloUscitaResponse.Return richiestaProtocolloUscita(
        @WebParam(name = "protocolloUscitaRequest", targetNamespace = "")
        it.linksmt.protocollo.ws.server.RichiestaProtocolloUscita.ProtocolloUscitaRequest protocolloUscitaRequest
    );
}
