update pratiche_eventi set stato_mail = null;
update pratica set stato_email = null;

update pratiche_eventi set stato_mail = (select id_stati_mail from lk_stati_mail where codice='E') where id_pratica_evento in (select distinct id_pratica_evento from email where stato = (select id_stati_mail from lk_stati_mail where codice='E') or stato =(select id_stati_mail from lk_stati_mail where codice='M'));

update pratiche_eventi set stato_mail = (select id_stati_mail from lk_stati_mail where codice='X') where id_pratica_evento in (select distinct e.id_pratica_evento from email e join (select id_pratica_evento from email group by id_pratica_evento having count(*) > 0) e1 on e.id_pratica_evento = e1.id_pratica_evento where e.id_pratica_evento in (select distinct id_pratica_evento from email where stato <> (select id_stati_mail from lk_stati_mail where codice='C') and stato <> (select id_stati_mail from lk_stati_mail where codice='E') and stato <> (select id_stati_mail from lk_stati_mail where codice='M')) and stato_mail <> (select id_stati_mail from lk_stati_mail where codice='E') or stato_mail is null);

update pratiche_eventi set stato_mail = (select id_stati_mail from lk_stati_mail where codice='C') where id_pratica_evento in (select x.id_pratica_evento from (select distinct p.id_pratica_evento, (select count(*) totale from email where id_pratica_evento = p.id_pratica_evento group by id_pratica_evento having count(*) > 0) totale,(select  count(*) numero from email where stato = (select id_stati_mail from lk_stati_mail where codice='C') and id_pratica_evento = p.id_pratica_evento group by id_pratica_evento having count(*) > 0) numero from email p) x where x.totale=x.numero);

update pratica set stato_email = (select id_stati_mail from lk_stati_mail where codice='E') where id_pratica in (select distinct id_pratica from pratiche_eventi where stato_mail=(select id_stati_mail from lk_stati_mail where codice='E'));

update pratica set stato_email = (select id_stati_mail from lk_stati_mail where codice='X') where id_pratica in (select distinct t1.id_pratica from (select distinct t.id_pratica, t.totale, ifnull(eventiok,0) ok, ifnull(eventiko,0) ko from (select id_pratica, (select count(*) from pratiche_eventi where id_pratica = pe.id_pratica and stato_mail is not null group by id_pratica having count(*) > 0) totale , (select count(*) from pratiche_eventi where id_pratica = pe.id_pratica and stato_mail = (select id_stati_mail from lk_stati_mail where codice='C') group by id_pratica having count(*) > 0) eventiok, (select count(*) from pratiche_eventi where id_pratica = pe.id_pratica and stato_mail = (select id_stati_mail from lk_stati_mail where codice='E') group by id_pratica having count(*) > 0) eventiko from pratiche_eventi pe) t where t.totale is not null) t1 where t1.ko = 0  and t1.totale <> t1.ok);

update pratica set stato_email = (select id_stati_mail from lk_stati_mail where codice='C') where id_pratica in (select x.id_pratica from (select distinct p.id_pratica, (select count(*) from pratiche_eventi where id_pratica = p.id_pratica and stato_mail is not null group by id_pratica having count(*) > 0) totale,(select  count(*) numero from pratiche_eventi where stato_mail = (select id_stati_mail from lk_stati_mail where codice='C') and id_pratica = p.id_pratica group by id_pratica having count(*) > 0) numero from pratiche_eventi p) x where x.totale=x.numero);