-- ATTENZIONE ESEGUIRE SOLO IN AMBIENTE DI TEST - SETTA I PARAMETRI PER TEST SU COMMERCIO
-- ATTENZIONE ESEGUIRE SOLO IN AMBIENTE DI TEST - SETTA I PARAMETRI PER TEST SU COMMERCIO
-- ATTENZIONE ESEGUIRE SOLO IN AMBIENTE DI TEST - SETTA I PARAMETRI PER TEST SU COMMERCIO
-- ATTENZIONE ESEGUIRE SOLO IN AMBIENTE DI TEST - SETTA I PARAMETRI PER TEST SU COMMERCIO

insert into plugin_configuration (name,value) values('commercio.tipocommercio.test','78');
insert into plugin_configuration (name,value) values('commercio.tipoprocedimento.test','003');

-- ATTENZIONE ESEGUIRE SOLO IN AMBIENTE DI TEST - SETTA I PARAMETRI PER TEST SU COMMERCIO
-- ATTENZIONE ESEGUIRE SOLO IN AMBIENTE DI TEST - SETTA I PARAMETRI PER TEST SU COMMERCIO
-- ATTENZIONE ESEGUIRE SOLO IN AMBIENTE DI TEST - SETTA I PARAMETRI PER TEST SU COMMERCIO
-- ATTENZIONE ESEGUIRE SOLO IN AMBIENTE DI TEST - SETTA I PARAMETRI PER TEST SU COMMERCIO
