INSERT INTO `lk_stati_pratica_organi_collegiali` (`id_stato_pratica_organi_collegiali`, `des_stato_pratica_organi_collegiali`, `codice`) VALUES ('1', 'Attivo', 'A');

INSERT INTO `lk_ruoli_commissione` (`id_ruolo_commissione`, `descrizione`, `peso`) VALUES ('1', 'Presidente', '1');
INSERT INTO `lk_ruoli_commissione` (`id_ruolo_commissione`, `descrizione`, `peso`) VALUES ('2', 'Segretario', '2');
INSERT INTO `lk_ruoli_commissione` (`id_ruolo_commissione`, `descrizione`, `peso`) VALUES ('3', 'Componente', '3');

INSERT INTO `lk_stato_pratica` (`descrizione`, `codice`, `grp_stato_pratica`) VALUES ('Conferenza dei servizi', 'CS', 'A');

INSERT INTO `processi_eventi` (`id_processo`,`cod_evento`,`des_evento`,`stato_post`,`id_tipo_mittente`,`id_tipo_destinatario`,`script_scadenza_evento`,`verso`,`flg_portale`,`flg_mail`,`flg_all_mail`,`flg_protocollazione`,`flg_ricevuta`,`flg_destinatari`,`flg_firmato`,`flg_apri_sottopratica`,`flg_destinatari_solo_enti`,`flg_visualizza_procedimenti`,`id_procedimento_riferimento`,`id_script_evento`,`id_script_protocollo`,`max_destinatari`,`oggetto_email`,`corpo_email`,`funzione_applicativa`,`flg_automatico`) select id_processo, 'CONF_SERV','Attiva Conferenza servizi', (select id_stato_pratica from lk_stato_pratica where codice='CS'), NULL,NULL,NULL,'O','S','N','N','N','N','N','N','N','N','N',NULL,NULL,NULL,NULL,NULL,NULL,'attivaConferenzaServizi','N' from processi where cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED');

insert into processi_steps (id_evento_trigger, id_evento_result, tipo_operazione) select eve.id_evento_trigger, eve.id_evento_result, 'ADD' from (select t.id_evento id_evento_trigger,t.id_processo id_processo_trigger, r.id_evento id_evento_result, r.id_processo id_processo_result from (select  pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='APE') t join ( select pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CONF_SERV' ) r on t.id_processo = r.id_processo) eve; 

insert into processi_steps (id_evento_trigger, id_evento_result, tipo_operazione) select eve.id_evento_trigger, eve.id_evento_result, 'SUB' from (select t.id_evento id_evento_trigger,t.id_processo id_processo_trigger, r.id_evento id_evento_result, r.id_processo id_processo_result from (select  pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CONF_SERV') t join ( select pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CONF_SERV' ) r on t.id_processo = r.id_processo) eve; 

INSERT INTO `configuration` (`name`, `value`) VALUES ('cross.pratica.diritti.segreteria.enabled', 'TRUE');

INSERT INTO `processi_eventi` (`id_processo`,`cod_evento`,`des_evento`,`stato_post`,`id_tipo_mittente`,`id_tipo_destinatario`,`script_scadenza_evento`,`verso`,`flg_portale`,`flg_mail`,`flg_all_mail`,`flg_protocollazione`,`flg_ricevuta`,`flg_destinatari`,`flg_firmato`,`flg_apri_sottopratica`,`flg_destinatari_solo_enti`,`flg_visualizza_procedimenti`,`id_procedimento_riferimento`,`id_script_evento`,`id_script_protocollo`,`max_destinatari`,`oggetto_email`,`corpo_email`,`funzione_applicativa`,`flg_automatico`) select id_processo, 'CHIUS_CONF_SERV','Chiusura Conferenza dei Servizi', (select id_stato_pratica from lk_stato_pratica where codice='A'), NULL,NULL,NULL,'I','S','N','S','N','N','N','N','N','N','N',NULL,NULL,NULL,NULL,NULL,NULL,'comunicazione','N' from processi where cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED');

insert into processi_steps (id_evento_trigger, id_evento_result, tipo_operazione) select eve.id_evento_trigger, eve.id_evento_result, 'ADD' from (select t.id_evento id_evento_trigger,t.id_processo id_processo_trigger, r.id_evento id_evento_result, r.id_processo id_processo_result from (select  pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CONF_SERV') t join ( select pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CHIUS_CONF_SERV' ) r on t.id_processo = r.id_processo) eve; 

insert into processi_steps (id_evento_trigger, id_evento_result, tipo_operazione) select eve.id_evento_trigger, eve.id_evento_result, 'SUB' from (select t.id_evento id_evento_trigger,t.id_processo id_processo_trigger, r.id_evento id_evento_result, r.id_processo id_processo_result from (select  pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CHIUS_CONF_SERV') t join ( select pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CHIUS_CONF_SERV' ) r on t.id_processo = r.id_processo) eve; 

insert into processi_steps (id_evento_trigger, id_evento_result, tipo_operazione) select eve.id_evento_trigger, eve.id_evento_result, 'SUB' from (select t.id_evento id_evento_trigger,t.id_processo id_processo_trigger, r.id_evento id_evento_result, r.id_processo id_processo_result from (select  pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CHIUPOS') t join ( select pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CHIUS_CONF_SERV' ) r on t.id_processo = r.id_processo) eve; 

insert into processi_steps (id_evento_trigger, id_evento_result, tipo_operazione) select eve.id_evento_trigger, eve.id_evento_result, 'SUB' from (select t.id_evento id_evento_trigger,t.id_processo id_processo_trigger, r.id_evento id_evento_result, r.id_processo id_processo_result from (select  pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CHIUNEG') t join ( select pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CHIUS_CONF_SERV' ) r on t.id_processo = r.id_processo) eve; 

insert into processi_steps (id_evento_trigger, id_evento_result, tipo_operazione) select eve.id_evento_trigger, eve.id_evento_result, 'SUB' from (select t.id_evento id_evento_trigger,t.id_processo id_processo_trigger, r.id_evento id_evento_result, r.id_processo id_processo_result from (select  pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CHIUPOS') t join ( select pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CONF_SERV' ) r on t.id_processo = r.id_processo) eve; 

insert into processi_steps (id_evento_trigger, id_evento_result, tipo_operazione) select eve.id_evento_trigger, eve.id_evento_result, 'SUB' from (select t.id_evento id_evento_trigger,t.id_processo id_processo_trigger, r.id_evento id_evento_result, r.id_processo id_processo_result from (select  pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CHIUNEG') t join ( select pe.id_evento, p.id_processo from processi_eventi pe join processi p on p.id_processo=pe.id_processo where p.cod_processo in ('AP_ORD','AP_AUTO','PDC','SCIAED') and pe.cod_evento='CONF_SERV' ) r on t.id_processo = r.id_processo) eve; 