package it.wego.cross.plugins.genova.commercio.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2014-06-27T12:26:45.249+02:00
 * Generated source version: 2.3.9
 * 
 */
@WebService(targetNamespace = "http://italysolution.com/Suap", name = "AggiornaSuapSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AggiornaSuapSoap {

    @WebResult(name = "AggiornaResult", targetNamespace = "http://italysolution.com/Suap")
    @RequestWrapper(localName = "Aggiorna", targetNamespace = "http://italysolution.com/Suap", className = "it.wego.cross.plugins.genova.commercio.service.Aggiorna")
    @WebMethod(operationName = "Aggiorna", action = "http://italysolution.com/Suap/Aggiorna")
    @ResponseWrapper(localName = "AggiornaResponse", targetNamespace = "http://italysolution.com/Suap", className = "it.wego.cross.plugins.genova.commercio.service.AggiornaResponse")
    public java.lang.String aggiorna(
        @WebParam(name = "user", targetNamespace = "http://italysolution.com/Suap")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "http://italysolution.com/Suap")
        java.lang.String password,
        @WebParam(name = "dati", targetNamespace = "http://italysolution.com/Suap")
        java.lang.String dati
    );
}
