package it.gov.impresainungiorno.schema.suap.ri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-20T10:56:27.091+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.impresainungiorno.gov.it/schema/suap/ri", name = "ProtocolloSUAP")
@XmlSeeAlso({it.gov.impresainungiorno.schema.base.ObjectFactory.class, it.gov.impresainungiorno.schema.suap.ri.spc.ObjectFactory.class, it.infocamere.protocollo.ejb.ObjectFactory.class})
public interface ProtocolloSUAP {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "comunicazioneREA", targetNamespace = "http://ejb.protocollo.infocamere.it/", className = "it.infocamere.protocollo.ejb.ComunicazioneREA")
    @WebMethod(action = "IscrizioneImpresaRiSpc")
    @ResponseWrapper(localName = "comunicazioneREAResponse", targetNamespace = "http://ejb.protocollo.infocamere.it/", className = "it.infocamere.protocollo.ejb.ComunicazioneREAResponse")
    public it.infocamere.protocollo.ejb.RispostaREA comunicazioneREA(
        @WebParam(name = "soggetti", targetNamespace = "")
        it.infocamere.protocollo.ejb.SoggettoSUAP soggetti,
        @WebParam(name = "pridPratica", targetNamespace = "")
        java.lang.String pridPratica,
        @WebParam(name = "suapReaXml", targetNamespace = "")
        it.infocamere.protocollo.ejb.AllegatoSUAPReaXml suapReaXml,
        @WebParam(name = "suapXml", targetNamespace = "")
        it.infocamere.protocollo.ejb.AllegatoSUAPXml suapXml,
        @WebParam(name = "allegati", targetNamespace = "")
        java.util.List<it.infocamere.protocollo.ejb.AllegatoSUAP> allegati,
        @WebParam(name = "visuraXML", targetNamespace = "")
        boolean visuraXML,
        @WebParam(name = "visuraPDF", targetNamespace = "")
        boolean visuraPDF
    ) throws ProtocolloSUAPException, PraticaSUAPException;
}
