package it.gov.impresainungiorno.schema.suap.ri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-20T10:56:27.075+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.impresainungiorno.gov.it/schema/suap/ri", name = "RichiestaIscrizioneImpresaRiSPC")
@XmlSeeAlso({it.gov.impresainungiorno.schema.base.ObjectFactory.class, it.gov.impresainungiorno.schema.suap.ri.spc.ObjectFactory.class, it.infocamere.protocollo.ejb.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RichiestaIscrizioneImpresaRiSPC {

    @WebResult(name = "IscrizioneImpresaRiSpcResponse", targetNamespace = "http://www.impresainungiorno.gov.it/schema/suap/ri/spc", partName = "IscrizioneImpresaRiSpcResponse")
    @WebMethod(operationName = "IscrizioneImpresaRiSpc", action = "IscrizioneImpresaRiSpc")
    public it.gov.impresainungiorno.schema.suap.ri.spc.IscrizioneImpresaRiSpcResponse iscrizioneImpresaRiSpc(
        @WebParam(partName = "IscrizioneImpresaRiSpcRequest", name = "IscrizioneImpresaRiSpcRequest", targetNamespace = "http://www.impresainungiorno.gov.it/schema/suap/ri/spc")
        it.gov.impresainungiorno.schema.suap.ri.spc.IscrizioneImpresaRiSpcRequest iscrizioneImpresaRiSpcRequest
    );
}
