package it.gov.impresainungiorno.schema.suap.ri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Servizio di integrazione tra Suap e Ri
 *
 * This class was generated by Apache CXF 2.5.2
 * 2012-11-20T10:56:27.099+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "ServizioIntegrazioneSuapRi", 
                  wsdlLocation = "comunicazioniRea_implementazione_erogatore.wsdl",
                  targetNamespace = "http://www.impresainungiorno.gov.it/schema/suap/ri") 
public class ServizioIntegrazioneSuapRi extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.impresainungiorno.gov.it/schema/suap/ri", "ServizioIntegrazioneSuapRi");
    public final static QName RichiestaIscrizioneImpresaRiSPC = new QName("http://www.impresainungiorno.gov.it/schema/suap/ri", "RichiestaIscrizioneImpresaRiSPC");
    public final static QName ProtocolloSUAP = new QName("http://www.impresainungiorno.gov.it/schema/suap/ri", "ProtocolloSUAP");
    static {
        URL url = ServizioIntegrazioneSuapRi.class.getResource("comunicazioniRea_implementazione_erogatore.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ServizioIntegrazioneSuapRi.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "comunicazioniRea_implementazione_erogatore.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ServizioIntegrazioneSuapRi(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServizioIntegrazioneSuapRi(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServizioIntegrazioneSuapRi() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RichiestaIscrizioneImpresaRiSPC
     */
    @WebEndpoint(name = "RichiestaIscrizioneImpresaRiSPC")
    public RichiestaIscrizioneImpresaRiSPC getRichiestaIscrizioneImpresaRiSPC() {
        return super.getPort(RichiestaIscrizioneImpresaRiSPC, RichiestaIscrizioneImpresaRiSPC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RichiestaIscrizioneImpresaRiSPC
     */
    @WebEndpoint(name = "RichiestaIscrizioneImpresaRiSPC")
    public RichiestaIscrizioneImpresaRiSPC getRichiestaIscrizioneImpresaRiSPC(WebServiceFeature... features) {
        return super.getPort(RichiestaIscrizioneImpresaRiSPC, RichiestaIscrizioneImpresaRiSPC.class, features);
    }
    /**
     *
     * @return
     *     returns ProtocolloSUAP
     */
    @WebEndpoint(name = "ProtocolloSUAP")
    public ProtocolloSUAP getProtocolloSUAP() {
        return super.getPort(ProtocolloSUAP, ProtocolloSUAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProtocolloSUAP
     */
    @WebEndpoint(name = "ProtocolloSUAP")
    public ProtocolloSUAP getProtocolloSUAP(WebServiceFeature... features) {
        return super.getPort(ProtocolloSUAP, ProtocolloSUAP.class, features);
    }

}
