// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package it.wego.cross.client.stub.inseriscifascicolo;


public class WSInserimentoFasc_service_ResponseStruct {
    protected java.lang.String serviceReturn;
    
    public WSInserimentoFasc_service_ResponseStruct() {
    }
    
    public WSInserimentoFasc_service_ResponseStruct(java.lang.String serviceReturn) {
        this.serviceReturn = serviceReturn;
    }
    
    public java.lang.String getServiceReturn() {
        return serviceReturn;
    }
    
    public void setServiceReturn(java.lang.String serviceReturn) {
        this.serviceReturn = serviceReturn;
    }
}
