// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package it.wego.cross.client.stub.inseriscifascicolo;

import com.sun.xml.rpc.client.HandlerChainImpl;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import javax.xml.namespace.QName;
import javax.xml.rpc.*;

public class WSInserimentoFascService_Impl extends com.sun.xml.rpc.client.BasicService implements WSInserimentoFascService {
    private static final QName serviceName = new QName("http://protocollotest.comune.genova.it/axis/services/WSInserimentoFasc", "WSInserimentoFascService");
    private static final QName ns1_WSInserimentoFasc_QNAME = new QName("http://protocollotest.comune.genova.it/axis/services/WSInserimentoFasc", "WSInserimentoFasc");
    private static final Class WSInserimentoFasc_PortClass = it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc.class;
    
    public WSInserimentoFascService_Impl() {
        super(serviceName, new QName[] {
                        ns1_WSInserimentoFasc_QNAME
                    },
            new it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFascService_SerializerRegistry().getRegistry());
        
    }
    
    @Override
    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_WSInserimentoFasc_QNAME) &&
                serviceDefInterface.equals(WSInserimentoFasc_PortClass)) {
                return getWSInserimentoFasc(null);
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    @Override
    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(WSInserimentoFasc_PortClass)) {
                return getWSInserimentoFasc(null);
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc getWSInserimentoFasc(Integer timeout) {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_WSInserimentoFasc_QNAME));
        handlerChain.setRoles(roles);
        it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_Stub stub = new it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_Stub(handlerChain, timeout);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
