// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package it.wego.cross.client.stub.inseriscifascicolo;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.streaming.*;
import javax.xml.namespace.QName;

public class WSInserimentoFasc_service_RequestStruct_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_codEnte_QNAME = new QName("", "codEnte");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SOAPConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_userid_QNAME = new QName("", "userid");
    private static final javax.xml.namespace.QName ns1_password_QNAME = new QName("", "password");
    private static final javax.xml.namespace.QName ns1_indirizzoIP_QNAME = new QName("", "indirizzoIP");
    private static final javax.xml.namespace.QName ns1_xml_QNAME = new QName("", "xml");
    private static final javax.xml.namespace.QName ns1_hash_QNAME = new QName("", "hash");
    private static final int myCODENTE_INDEX = 0;
    private static final int myUSERID_INDEX = 1;
    private static final int myPASSWORD_INDEX = 2;
    private static final int myINDIRIZZOIP_INDEX = 3;
    private static final int myXML_INDEX = 4;
    private static final int myHASH_INDEX = 5;
    
    public WSInserimentoFasc_service_RequestStruct_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns2_string_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct instance = new it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct();
        it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        for (int i=0; i<6; i++) {
            elementName = reader.getName();
            if (reader.getState() == XMLReader.END) {
                break;
            }
            if (elementName.equals(ns1_codEnte_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_codEnte_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCODENTE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setCodEnte((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_userid_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_userid_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myUSERID_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setUserid((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_password_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_password_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPASSWORD_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPassword((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_indirizzoIP_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_indirizzoIP_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myINDIRIZZOIP_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setIndirizzoIP((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_xml_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_xml_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myXML_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setXml((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_hash_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_hash_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myHASH_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setHash((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            } else {
                throw new DeserializationException("soap.unexpectedElementName", new Object[] {ns1_hash_QNAME, elementName});
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct instance = (it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct instance = (it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct)obj;
        
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getCodEnte(), ns1_codEnte_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getUserid(), ns1_userid_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getPassword(), ns1_password_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getIndirizzoIP(), ns1_indirizzoIP_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getXml(), ns1_xml_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getHash(), ns1_hash_QNAME, null, writer, context);
    }
}
