// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package it.wego.cross.client.stub.inseriscifascicolo;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class WSInserimentoFasc_service_RequestStruct_SOAPBuilder implements SOAPInstanceBuilder {
    private it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct _instance;
    private java.lang.String codEnte;
    private java.lang.String userid;
    private java.lang.String password;
    private java.lang.String indirizzoIP;
    private java.lang.String xml;
    private java.lang.String hash;
    private static final int myCODENTE_INDEX = 0;
    private static final int myUSERID_INDEX = 1;
    private static final int myPASSWORD_INDEX = 2;
    private static final int myINDIRIZZOIP_INDEX = 3;
    private static final int myXML_INDEX = 4;
    private static final int myHASH_INDEX = 5;
    
    public WSInserimentoFasc_service_RequestStruct_SOAPBuilder() {
    }
    
    public void setCodEnte(java.lang.String codEnte) {
        this.codEnte = codEnte;
    }
    
    public void setUserid(java.lang.String userid) {
        this.userid = userid;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public void setIndirizzoIP(java.lang.String indirizzoIP) {
        this.indirizzoIP = indirizzoIP;
    }
    
    public void setXml(java.lang.String xml) {
        this.xml = xml;
    }
    
    public void setHash(java.lang.String hash) {
        this.hash = hash;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myCODENTE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myUSERID_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPASSWORD_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myINDIRIZZOIP_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myXML_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myHASH_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myCODENTE_INDEX:
                    _instance.setCodEnte((java.lang.String)memberValue);
                    break;
                case myUSERID_INDEX:
                    _instance.setUserid((java.lang.String)memberValue);
                    break;
                case myPASSWORD_INDEX:
                    _instance.setPassword((java.lang.String)memberValue);
                    break;
                case myINDIRIZZOIP_INDEX:
                    _instance.setIndirizzoIP((java.lang.String)memberValue);
                    break;
                case myXML_INDEX:
                    _instance.setXml((java.lang.String)memberValue);
                    break;
                case myHASH_INDEX:
                    _instance.setHash((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (it.wego.cross.client.stub.inseriscifascicolo.WSInserimentoFasc_service_RequestStruct)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
