package it.wego.cross.avbari.catasto.client;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-04-10T09:17:12.052+02:00
 * Generated source version: 2.3.9
 * 
 */
@WebServiceClient(name = "Catasto", 
                  targetNamespace = "http://tempuri.org/") 
public class Catasto extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "Catasto");
    public final static QName BasicHttpsBindingICatasto = new QName("http://tempuri.org/", "BasicHttpsBinding_ICatasto");
    public final static QName BasicHttpBindingICatasto = new QName("http://tempuri.org/", "BasicHttpBinding_ICatasto");
    private static final Logger logger = LoggerFactory.getLogger(Catasto.class.getName());
    static {
        URL url = null;
        String wsdlClasspathUrl = "it/wego/cross/avbari/linksmt/wsdl_produzione/02_05_2018/catasto/wsdl_catasto.wsdl";
        try {
        	Resource res = new ClassPathResource(wsdlClasspathUrl);
            url = res.getURL();
        } catch (Exception e) {
        	logger.warn("Impossibile inizializzare l'URL del WS per il catasto {} ", wsdlClasspathUrl, e);
        }
        WSDL_LOCATION = url;
    }

    public Catasto(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Catasto(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Catasto() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Catasto(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Catasto(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Catasto(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ICatasto
     */
    @WebEndpoint(name = "BasicHttpsBinding_ICatasto")
    public ICatasto getBasicHttpsBindingICatasto() {
        return super.getPort(BasicHttpsBindingICatasto, ICatasto.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICatasto
     */
    @WebEndpoint(name = "BasicHttpsBinding_ICatasto")
    public ICatasto getBasicHttpsBindingICatasto(WebServiceFeature... features) {
        return super.getPort(BasicHttpsBindingICatasto, ICatasto.class, features);
    }
    /**
     *
     * @return
     *     returns ICatasto
     */
    @WebEndpoint(name = "BasicHttpBinding_ICatasto")
    public ICatasto getBasicHttpBindingICatasto() {
        return super.getPort(BasicHttpBindingICatasto, ICatasto.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICatasto
     */
    @WebEndpoint(name = "BasicHttpBinding_ICatasto")
    public ICatasto getBasicHttpBindingICatasto(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingICatasto, ICatasto.class, features);
    }

}
