package it.wego.cross.avbari.catasto.client;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-04-09T12:04:10.040+02:00
 * Generated source version: 2.3.9
 * 
 */
@WebServiceClient(name = "CatastoTerreniService", 
                  targetNamespace = "http://tempuri.org/") 
public class CatastoTerreniService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "CatastoTerreniService");
    public final static QName BasicHttpBindingICatastoTerreniService = new QName("http://tempuri.org/", "BasicHttpBinding_ICatastoTerreniService");
    public final static QName BasicHttpsBindingICatastoTerreniService = new QName("http://tempuri.org/", "BasicHttpsBinding_ICatastoTerreniService");
    private static final Logger logger = LoggerFactory.getLogger(CatastoTerreniService.class.getName());
    static {
        URL url = null;
        String wsdlClasspathUrl = "it/wego/cross/avbari/linksmt/wsdl_produzione/02_05_2018/catastoTerreni/wsdl_catasto_terreni.wsdl";
        try {
        	Resource res = new ClassPathResource(wsdlClasspathUrl);
            url = res.getURL();
        } catch (Exception e) {
        	logger.warn("Impossibile inizializzare l'URL del WS per le determine accedendo al file del classpath {} ", wsdlClasspathUrl, e);
        }
        WSDL_LOCATION = url;
    }

    public CatastoTerreniService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CatastoTerreniService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatastoTerreniService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CatastoTerreniService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CatastoTerreniService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CatastoTerreniService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ICatastoTerreniService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICatastoTerreniService")
    public ICatastoTerreniService getBasicHttpBindingICatastoTerreniService() {
        return super.getPort(BasicHttpBindingICatastoTerreniService, ICatastoTerreniService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICatastoTerreniService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICatastoTerreniService")
    public ICatastoTerreniService getBasicHttpBindingICatastoTerreniService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingICatastoTerreniService, ICatastoTerreniService.class, features);
    }
    /**
     *
     * @return
     *     returns ICatastoTerreniService
     */
    @WebEndpoint(name = "BasicHttpsBinding_ICatastoTerreniService")
    public ICatastoTerreniService getBasicHttpsBindingICatastoTerreniService() {
        return super.getPort(BasicHttpsBindingICatastoTerreniService, ICatastoTerreniService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICatastoTerreniService
     */
    @WebEndpoint(name = "BasicHttpsBinding_ICatastoTerreniService")
    public ICatastoTerreniService getBasicHttpsBindingICatastoTerreniService(WebServiceFeature... features) {
        return super.getPort(BasicHttpsBindingICatastoTerreniService, ICatastoTerreniService.class, features);
    }

}
