package it.wego.cross.avbari.catasto.client;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-04-09T10:36:34.113+02:00
 * Generated source version: 2.3.9
 * 
 */
@WebServiceClient(name = "CatastoFabbricatiService", 
                  targetNamespace = "http://tempuri.org/") 
public class CatastoFabbricatiService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "CatastoFabbricatiService");
    public final static QName BasicHttpsBindingICatastoFabbricatiService = new QName("http://tempuri.org/", "BasicHttpsBinding_ICatastoFabbricatiService");
    public final static QName BasicHttpBindingICatastoFabbricatiService = new QName("http://tempuri.org/", "BasicHttpBinding_ICatastoFabbricatiService");
    private static final Logger logger = LoggerFactory.getLogger(CatastoFabbricatiService.class.getName());
    static {
        URL url = null;
        String wsdlClasspathUrl = "it/wego/cross/avbari/linksmt/wsdl_produzione/02_05_2018/catastoFabbricati/wsdl_catasto_fabbricati.wsdl";
        try {
        	Resource res = new ClassPathResource(wsdlClasspathUrl);
            url = res.getURL();
        } catch (Exception e) {
        	logger.warn("Impossibile inizializzare l'URL del WS per il catasto fabbricati accedendo al file del classpath {} ", wsdlClasspathUrl, e);
        }
        WSDL_LOCATION = url;
    }

    public CatastoFabbricatiService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CatastoFabbricatiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatastoFabbricatiService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CatastoFabbricatiService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CatastoFabbricatiService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CatastoFabbricatiService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ICatastoFabbricatiService
     */
    @WebEndpoint(name = "BasicHttpsBinding_ICatastoFabbricatiService")
    public ICatastoFabbricatiService getBasicHttpsBindingICatastoFabbricatiService() {
        return super.getPort(BasicHttpsBindingICatastoFabbricatiService, ICatastoFabbricatiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICatastoFabbricatiService
     */
    @WebEndpoint(name = "BasicHttpsBinding_ICatastoFabbricatiService")
    public ICatastoFabbricatiService getBasicHttpsBindingICatastoFabbricatiService(WebServiceFeature... features) {
        return super.getPort(BasicHttpsBindingICatastoFabbricatiService, ICatastoFabbricatiService.class, features);
    }
    /**
     *
     * @return
     *     returns ICatastoFabbricatiService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICatastoFabbricatiService")
    public ICatastoFabbricatiService getBasicHttpBindingICatastoFabbricatiService() {
        return super.getPort(BasicHttpBindingICatastoFabbricatiService, ICatastoFabbricatiService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICatastoFabbricatiService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICatastoFabbricatiService")
    public ICatastoFabbricatiService getBasicHttpBindingICatastoFabbricatiService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingICatastoFabbricatiService, ICatastoFabbricatiService.class, features);
    }

}
