
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.wego.cross.avbari.catasto.client;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-04-09T10:36:34.060+02:00
 * Generated source version: 2.3.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "CatastoFabbricatiService",
                      portName = "BasicHttpsBinding_ICatastoFabbricatiService",
                      targetNamespace = "http://tempuri.org/",
                      endpointInterface = "it.wego.cross.avbari.catasto.client.ICatastoFabbricatiService")
                      
public class ICatastoFabbricatiServiceImpl implements ICatastoFabbricatiService {

    private static final Logger LOG = LoggerFactory.getLogger(ICatastoFabbricatiServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see it.wego.cross.avbari.catasto.client.ICatastoFabbricatiService#process(java.lang.String  data )*
     */
    public java.lang.String process(java.lang.String data) { 

        try {
            java.lang.String _return = "";
            if( LOG.isInfoEnabled() )
            {
            	LOG.info("ESECUZIONE METODO [{}] CON DATA [{}] RESULT [{}]", "process", data, _return);
            }
            return _return;
        } catch (java.lang.Exception ex) {
            if( LOG.isErrorEnabled() )
            {
            	LOG.error("ERRORE NELL'ESECUZIONE METODO [{}] CON DATA [{}]", "process", data, ex);
            }
            throw new RuntimeException(ex);
        }
    }

}
