package it.wego.cross.avbari.catasto.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-04-09T10:36:34.100+02:00
 * Generated source version: 2.3.9
 * 
 */
@WebService(targetNamespace = "http://webservice.backend.people.it/", name = "ICatastoFabbricatiService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICatastoFabbricatiService {

    @WebResult(name = "return", targetNamespace = "http://webservice.backend.people.it/")
    @Action(input = "process", output = "http://webservice.backend.people.it/ICatastoFabbricatiService/processResponse")
    @RequestWrapper(localName = "process", targetNamespace = "http://webservice.backend.people.it/", className = "it.wego.cross.avbari.catasto.client.Process")
    @WebMethod(action = "process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://webservice.backend.people.it/", className = "it.wego.cross.avbari.catasto.client.ProcessResponse")
    public java.lang.String process(
        @WebParam(name = "data", targetNamespace = "http://webservice.backend.people.it/")
        java.lang.String data
    );
}
