
package it.wego.cross.avbari.atti.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-02-17T11:54:00.173+01:00
 * Generated source version: 2.3.9
 * 
 */
public final class DeterminaServer_DeterminaServerImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.server.ws.amministrazioneatti.avt.linksmt.it/", "DeterminaServerImplService");

    private DeterminaServer_DeterminaServerImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DeterminaServerImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DeterminaServerImplService ss = new DeterminaServerImplService(wsdlURL, SERVICE_NAME);
        DeterminaServer port = ss.getDeterminaServerImplPort();  
        
        {
        System.out.println("Invoking getDocumentoDetermina...");
        it.wego.cross.avbari.atti.client.GetDocumentoDetermina.DocumentoDeterminaRequest _getDocumentoDetermina_documentoDeterminaRequest = null;
        it.wego.cross.avbari.atti.client.GetDocumentoDeterminaResponse.Return _getDocumentoDetermina__return = port.getDocumentoDetermina(_getDocumentoDetermina_documentoDeterminaRequest);
        System.out.println("getDocumentoDetermina.result=" + _getDocumentoDetermina__return);


        }
        {
        System.out.println("Invoking getAllegatiDetermina...");
        it.wego.cross.avbari.atti.client.GetAllegatiDetermina.AllegatiDeterminaRequest _getAllegatiDetermina_allegatiDeterminaRequest = null;
        it.wego.cross.avbari.atti.client.GetAllegatiDeterminaResponse.Return _getAllegatiDetermina__return = port.getAllegatiDetermina(_getAllegatiDetermina_allegatiDeterminaRequest);
        System.out.println("getAllegatiDetermina.result=" + _getAllegatiDetermina__return);


        }

        System.exit(0);
    }

}
