
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.wego.cross.avbari.atti.client;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-02-17T11:54:00.232+01:00
 * Generated source version: 2.3.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "DeterminaServerImplService",
                      portName = "DeterminaServerImplPort",
                      targetNamespace = "http://impl.server.ws.amministrazioneatti.avt.linksmt.it/",
                      endpointInterface = "it.wego.cross.avbari.atti.client.DeterminaServer")
                      
public class DeterminaServerImpl implements DeterminaServer {

    private static final Logger LOG = LoggerFactory.getLogger(DeterminaServerImpl.class.getName());

    /* (non-Javadoc)
     * @see it.wego.cross.avbari.atti.client.DeterminaServer#getDocumentoDetermina(it.wego.cross.avbari.atti.client.GetDocumentoDetermina.DocumentoDeterminaRequest  documentoDeterminaRequest )*
     */
    public it.wego.cross.avbari.atti.client.GetDocumentoDeterminaResponse.Return getDocumentoDetermina(it.wego.cross.avbari.atti.client.GetDocumentoDetermina.DocumentoDeterminaRequest documentoDeterminaRequest) { 

        try {
            it.wego.cross.avbari.atti.client.GetDocumentoDeterminaResponse.Return _return = null;
            if( LOG.isInfoEnabled() )
            {
            	LOG.info("ESECUZIONE METODO [{}] CON REQUEST [{}] RISULTATO [{}]", "getDocumentoDetermina", documentoDeterminaRequest, _return);
            }
            return _return;
        } catch (java.lang.Exception ex) {
            if( LOG.isErrorEnabled() )
            {
            	LOG.error("ECCEZIONE NELL'ESECUZIONE METODO [{}] CON REQUEST [{}]", "getDocumentoDetermina", documentoDeterminaRequest, ex);
            }
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.wego.cross.avbari.atti.client.DeterminaServer#getAllegatiDetermina(it.wego.cross.avbari.atti.client.GetAllegatiDetermina.AllegatiDeterminaRequest  allegatiDeterminaRequest )*
     */
    public it.wego.cross.avbari.atti.client.GetAllegatiDeterminaResponse.Return getAllegatiDetermina(it.wego.cross.avbari.atti.client.GetAllegatiDetermina.AllegatiDeterminaRequest allegatiDeterminaRequest) { 
        try {
            it.wego.cross.avbari.atti.client.GetAllegatiDeterminaResponse.Return _return = null;
            if( LOG.isInfoEnabled() )
            {
            	LOG.info("ESECUZIONE METODO [{}] CON REQUEST [{}] RISULTATO [{}]", "getAllegatiDetermina", allegatiDeterminaRequest, _return);
            }            
            return _return;
        } catch (java.lang.Exception ex) {
            if( LOG.isErrorEnabled() )
            {
            	LOG.error("ECCEZIONE NELL'ESECUZIONE METODO [{}] CON REQUEST [{}]", "getAllegatiDetermina", allegatiDeterminaRequest, ex);
            }
            throw new RuntimeException(ex);
        }
    }

}
