
package it.wego.cross.webservices.cxf.cripal;

import it.wego.cross.webservices.cxf.*;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CripalPraticheService", targetNamespace = "http://www.wego.it/cross")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    it.wego.cross.webservices.cxf.ObjectFactory.class
})
public interface CripalPraticheService {


    /**
     * 
     * @param parameters
     * @return
     *     returns it.wego.cross.PraticaDetailResponse
     */
    @WebMethod
    @WebResult(name = "PraticaDetailResponse", targetNamespace = "http://www.wego.it/cross", partName = "parameters")
    public PraticaDetailResponse getPraticaDetail(
        @WebParam(name = "PraticaDetailRequest", targetNamespace = "http://www.wego.it/cross", partName = "parameters")
        PraticaDetailRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns it.wego.cross.ElencoPraticheResponse
     */
    @WebMethod
    @WebResult(name = "ElencoPraticheResponse", targetNamespace = "http://www.wego.it/cross", partName = "parameters")
    public ElencoPraticheResponse getPraticheList(
        @WebParam(name = "ElencoPraticheRequest", targetNamespace = "http://www.wego.it/cross", partName = "parameters")
        ElencoPraticheRequest parameters);

}
